#!/bin/sh
# Assembles the September 2026 release migrations, one file per project, from the reviewed pieces.
#   sh legacy/scripts/build-release-sql.sh
#   TEST_2026-09-12.sql  — L18 environment marker, T01 mark TEST, L19 best of three, L20 waiver records, T02 publish v2,
#                          L21 exact privileges on the new tables.
#                          Run in the TEST project's SQL editor.
#   PROD_2026-09-12.sql  — L18, P01 mark PRODUCTION, L19, L20 (v1 stays the current waiver), L21. PREPARED ONLY: run on the
#                          production project as part of an approved release, after a verified backup (docs/28).
# Both end with verify.sql; every row must say OK. The production file never contains a T0x step, and the TEST file
# never contains a P0x step (checked below).
set -eu
cd "$(dirname "$0")/../.."
python3 legacy/scripts/build-waiver-records.py >/dev/null
python3 legacy/scripts/build-rollback-sql.py >/dev/null   # ROLLBACK_2026-09-12.sql (prepared only; docs/28 section 9)
build() { out=$1; shift; label=$1; shift
  {
    echo "-- Maplewood league release, September 2026 — $label. Generated by legacy/scripts/build-release-sql.sh; do not edit."
    for f in "$@"; do echo; echo "-- ═══════════ $f ═══════════"; cat "legacy/migrations/$f.sql"; done
    echo; echo "-- ═══════════ verify ═══════════"; cat legacy/migrations/verify.sql
  } > "legacy/migrations/$out"
  echo "wrote legacy/migrations/$out ($(wc -l < "legacy/migrations/$out") lines)"
}
build TEST_2026-09-12.sql "TEST project (wgolevihkvmosajumzvl)" L18_environment T01_mark_test L19_best_of_three L20_waiver_records T02_publish_waiver_v2 L21_new_table_privileges
build PROD_2026-09-12.sql "PRODUCTION project (bwepvxelvwgwxrnaglrx) — run only after approval and a verified backup" L18_environment P01_mark_production L19_best_of_three L20_waiver_records L21_new_table_privileges
if grep -q "═ T0[0-9]" legacy/migrations/PROD_2026-09-12.sql; then echo "refusing: a TEST-only step is in the production file"; exit 1; fi
if grep -q "═ P0[0-9]" legacy/migrations/TEST_2026-09-12.sql; then echo "refusing: a production-only step is in the TEST file"; exit 1; fi
