#!/usr/bin/env python3
"""Builds migration L20 (waiver versions and acceptance records) from the wording files in legacy/waiver/.

    python3 legacy/scripts/build-waiver-records.py

legacy/waiver/2026-09-v1.txt is extracted, once, from the sign-up form as committed before this release (aebbc28, the
wording production shows) and is never edited afterwards. Newer versions are written by hand as new files. The wording
format: "# " title line, "## " section headings, "• " list items, blank lines between paragraphs. The database stores
each file's text exactly (no trailing newline) and computes its SHA-256; the site shows that text and sends the digest
back when someone accepts, so a record always names the exact words that were on screen."""
import html as H, pathlib, re, subprocess, sys
ROOT = pathlib.Path(__file__).resolve().parents[2]
W = ROOT / "legacy/waiver"
V1 = W / "2026-09-v1.txt"

def extract_v1():
    src = subprocess.run(["git", "-C", str(ROOT), "show", "aebbc28:index.html"], capture_output=True, text=True, check=True).stdout
    a = src.index('<div class="waiver-box">') + len('<div class="waiver-box">'); b = src.index("</div>", a)
    box = src[a:b]
    box = re.sub(r"<h4>(.*?)</h4>", lambda m: "\n\n## " + m.group(1) + "\n\n", box, flags=re.S)
    box = re.sub(r"<br\s*/?>\s*", "\n", box)
    box = box.replace("</p>", "\n\n")
    box = re.sub(r"<[^>]+>", "", box)
    lines = [H.unescape(l).strip() for l in box.split("\n")]
    text = re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()
    text = "# " + text                                    # the first line is the league's name
    accept = re.search(r'<input type="checkbox" id="w1">\s*<span[^>]*>(.*?)</span>', src, re.S).group(1)
    sig = re.search(r'<div style="font-size:11px;color:var\(--muted\);margin-top:4px;">(⚠️ By typing your name[^<]*)</div>', src).group(1)
    text += "\n\n## Acceptance\n" + H.unescape(re.sub(r"<[^>]+>", "", accept)).strip() + "\n" + sig.strip()
    return text

if not V1.exists():
    V1.write_text(extract_v1() + "\n")
    print(f"extracted {V1.relative_to(ROOT)}")

VERSIONS = [
    ("2026-09-v1", "Liability Waiver, Activity Release and Payment Policy", True,
     "The wording on the 2026-27 sign-up form before acceptance records began (as committed in aebbc28 and shown on the league site). That form also required a separate payment acknowledgement box on this step ($400 for regulars, $20 per session for spares). No individual acceptance of this version was recorded."),
    ("2026-09-v2", "Release of Liability, Waiver of Claims, Assumption of Risk and Consent", False,
     "Revised draft after the Ontario review in docs/28. Have an Ontario lawyer review it before it becomes the current version on the league site."),
]
body = {v: (W / f"{v}.txt").read_text().rstrip("\n") for v, *_ in VERSIONS}
for v, t in body.items():
    assert "$wv$" not in t and "\r" not in t, v
    assert t.startswith("# ") and "\n## Acceptance\n" in t, f"{v}: needs a title line and an Acceptance section"

ins = ",\n".join(f"  ('{v}','{title}',$wv${body[v]}$wv$,{'true' if cur else 'false'},'{note.replace(chr(39), chr(39) * 2)}')" for v, title, cur, note in VERSIONS)
sql = f"""-- L20: waiver wording versions, and an acceptance record for every agreement. GENERATED by
-- legacy/scripts/build-waiver-records.py from legacy/waiver/*.txt — change those files, then rebuild.
--   waiver_versions     every wording ever shown, kept permanently; the database computes each one's SHA-256 and
--                       refuses any change to the wording (publish a new version instead). One is current.
--   waiver_acceptances  who accepted which version, when (UTC, plus the device's time zone), how (the registration
--                       form or a later acceptance of an updated version), the typed signature, adult or guardian,
--                       and the separate photo/video choice (empty when the wording offered none). Never updated or deleted; if a player record is deleted
--                       the link is cleared and the record stays. Organizer reads all; a player reads only their own.
--   register_me         now also records the acceptance, and refuses wording that is not the current version or
--                       whose digest does not match what the page showed. accept_waiver records an updated version.
--   publish_waiver_version  the organizer switches which version new sign-ups see.
-- Older registrations are not given acceptance records: consent is never back-filled.
begin;
create table if not exists public.waiver_versions(
  version text primary key check (version ~ '^[0-9]{{4}}-[0-9]{{2}}-v[0-9]+$'),
  title text not null,
  body text not null,
  sha256 text not null default '',
  published_at timestamptz not null default now(),
  is_current boolean not null default false,
  note text not null default '');
create unique index if not exists waiver_versions_one_current on public.waiver_versions(is_current) where is_current;
alter table public.waiver_versions enable row level security;
revoke all on public.waiver_versions from public,anon,authenticated;
drop policy if exists "signed-in users read waiver wording" on public.waiver_versions;
create policy "signed-in users read waiver wording" on public.waiver_versions for select to authenticated using(true);
grant select on public.waiver_versions to authenticated,service_role;
create or replace function public.waiver_versions_guard() returns trigger language plpgsql set search_path='' as $$ begin
 if tg_op='DELETE' then raise exception 'Waiver versions are kept permanently' using errcode='42501'; end if;
 if tg_op='UPDATE' and (new.version<>old.version or new.title<>old.title or new.body<>old.body or new.published_at<>old.published_at) then
  raise exception 'Waiver wording is never rewritten — publish a new version instead' using errcode='42501'; end if;
 new.sha256=encode(sha256(convert_to(new.body,'UTF8')),'hex');   -- always the database's own digest of the wording
 return new;
end $$;
drop trigger if exists waiver_versions_guard on public.waiver_versions;
create trigger waiver_versions_guard before insert or update or delete on public.waiver_versions for each row execute function public.waiver_versions_guard();

create table if not exists public.waiver_acceptances(
  id bigint generated always as identity primary key,
  player_id bigint references public.players(id) on delete set null,
  user_id uuid,
  email text not null,
  participant_name text not null,
  typed_signature text not null,
  waiver_version text not null references public.waiver_versions(version),
  waiver_sha256 text not null,
  accepted_at timestamptz not null default now(),
  client_timezone text not null default '',
  client_utc_offset_minutes int,
  action text not null check (action in ('registration','updated-version')),
  age_declaration text not null default 'adult' check (age_declaration in ('adult','guardian')),
  minor_name text not null default '',
  media_consent boolean,                              -- null: no separate photo/video choice was offered
  registration_ref text not null default '',
  user_agent text not null default '');
create index if not exists waiver_acceptances_player on public.waiver_acceptances(player_id);
create index if not exists waiver_acceptances_user on public.waiver_acceptances(user_id);
alter table public.waiver_acceptances enable row level security;
revoke all on public.waiver_acceptances from public,anon,authenticated;
drop policy if exists "organizer reads all acceptances, a player their own" on public.waiver_acceptances;
create policy "organizer reads all acceptances, a player their own" on public.waiver_acceptances for select to authenticated using(public.is_admin() or user_id=auth.uid());
grant select on public.waiver_acceptances to authenticated,service_role;
create or replace function public.waiver_acceptances_guard() returns trigger language plpgsql set search_path='' as $$ begin
 if tg_op='DELETE' then raise exception 'Waiver acceptance records are kept permanently' using errcode='42501'; end if;
 -- The only change allowed: the player record was deleted, so the link is cleared; the record itself stays as it was.
 if not (new.player_id is null and old.player_id is not null and (to_jsonb(new)-'player_id')=(to_jsonb(old)-'player_id')) then
  raise exception 'Waiver acceptance records are never changed' using errcode='42501'; end if;
 return new;
end $$;
drop trigger if exists waiver_acceptances_guard on public.waiver_acceptances;
create trigger waiver_acceptances_guard before update or delete on public.waiver_acceptances for each row execute function public.waiver_acceptances_guard();

-- Records one acceptance after checking it names the current wording exactly. Called only by the two functions below.
create or replace function public.record_waiver_acceptance(p_player bigint,p_email text,p_name text,p_version text,p_sha text,p_sig text,p_tz text,p_offset int,p_action text,p_age text,p_minor text,p_media boolean,p_ua text) returns bigint language plpgsql security definer set search_path='' as $$
declare wv public.waiver_versions; i bigint; begin
 select * into wv from public.waiver_versions where version=coalesce(p_version,'');
 if wv.version is null then raise exception 'The waiver on your screen is out of date — reload the page and read the current version' using errcode='22023'; end if;
 if not wv.is_current then raise exception 'The waiver was updated while you were registering — reload the page and read the current version' using errcode='22023'; end if;
 if lower(coalesce(p_sha,''))<>wv.sha256 then raise exception 'The waiver text on your screen does not match version % — reload the page and try again',wv.version using errcode='22023'; end if;
 if length(trim(coalesce(p_sig,''))) not between 2 and 80 then raise exception 'Type your full name to sign the waiver' using errcode='22023'; end if;
 if coalesce(p_age,'adult') not in ('adult','guardian') then raise exception 'Choose whether you are 18 or older or a parent or guardian' using errcode='22023'; end if;
 if p_age='guardian' and length(trim(coalesce(p_minor,''))) not between 2 and 80 then raise exception 'Enter the name of the participant under 18' using errcode='22023'; end if;
 insert into public.waiver_acceptances(player_id,user_id,email,participant_name,typed_signature,waiver_version,waiver_sha256,client_timezone,client_utc_offset_minutes,action,age_declaration,minor_name,media_consent,registration_ref,user_agent)
 values(p_player,auth.uid(),coalesce(p_email,''),trim(p_name),trim(p_sig),wv.version,wv.sha256,left(coalesce(p_tz,''),64),case when p_offset between -840 and 840 then p_offset end,p_action,coalesce(p_age,'adult'),
        case when p_age='guardian' then left(trim(p_minor),80) else '' end,p_media,'REG-'||coalesce(p_player::text,'?')||'-'||to_char(now() at time zone 'UTC','YYYYMMDD"T"HH24MISS"Z"'),left(coalesce(p_ua,''),300))
 returning id into i;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'waiver.accepted',coalesce(p_player::text,''),jsonb_build_object('version',wv.version,'action',p_action,'acceptance',i));
 return i;
end $$;
revoke all on function public.record_waiver_acceptance(bigint,text,text,text,text,text,text,int,text,text,text,boolean,text) from public,anon,authenticated;

drop function if exists public.register_me(text,text,text,text,text,text,text);
create or replace function public.register_me(p_name text,p_phone text,p_emergency text,p_medical text,p_sig text,p_membership text,p_payment text default '',
  p_waiver_version text default '',p_waiver_sha text default '',p_waiver_sig text default '',p_tz text default '',p_offset int default null,p_age text default 'adult',p_minor text default '',p_media boolean default null,p_ua text default '')
returns bigint language plpgsql security definer set search_path='' as $$ declare em text; inv public.invitations; existing public.players; pid bigint; pay text; begin
 select lower(trim(email)) into em from auth.users where id=auth.uid() and email_confirmed_at is not null;
 if em is null then raise exception 'Verified sign-in email required' using errcode='42501';end if;
 select * into inv from public.invitations where email=em;
 select * into existing from public.players where user_id=auth.uid() or (user_id is null and lower(email)=em) order by user_id is not null desc limit 1;
 if existing.id is null and inv.email is null and not public.is_admin_any_factor() then raise exception 'Registration is closed. This link is for players Christy has confirmed; contact the organizer if you were accepted.' using errcode='42501';end if;
 if p_name is null or length(trim(p_name)) not between 2 and 80 or coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 or coalesce(length(p_sig),0)>200000 then raise exception 'Invalid registration details';end if;
 pay=case when p_payment in ('paid_full','will_pay','per_session') then p_payment else '' end;
 if existing.id is null then
  insert into public.players(name,email,phone,emergency,medical,sig,waiver_signed,paid,current_court,highest_court,season_wins,season_losses,games_played,membership_type,approved,waitlisted,registered_at,user_id,declared_payment)
  values(trim(p_name),em,coalesce(p_phone,''),coalesce(p_emergency,''),coalesce(p_medical,''),coalesce(p_sig,''),p_sig is not null and p_sig<>'',false,0,0,0,0,0,coalesce(inv.membership_type,p_membership,'regular'),false,false,now(),auth.uid(),pay) returning id into pid;
 else
  update public.players set name=trim(p_name),phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),sig=case when p_sig is not null and p_sig<>'' then p_sig else sig end,waiver_signed=(p_sig is not null and p_sig<>'') or waiver_signed,membership_type=coalesce(inv.membership_type,membership_type),registered_at=now(),user_id=auth.uid(),declared_payment=case when pay<>'' then pay else declared_payment end,updated_at=now() where id=existing.id returning id into pid;
 end if;
 perform public.record_waiver_acceptance(pid,em,p_name,p_waiver_version,p_waiver_sha,p_waiver_sig,p_tz,p_offset,'registration',p_age,p_minor,p_media,p_ua);
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'player.registered',pid::text,jsonb_build_object('payment',pay,'waiver',p_waiver_version));
 return pid;
end $$;
revoke all on function public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text) from public,anon;
grant execute on function public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text) to authenticated;

-- A registered player accepts a newer version (once per version).
create or replace function public.accept_waiver(p_version text,p_sha text,p_sig text,p_tz text default '',p_offset int default null,p_age text default 'adult',p_minor text default '',p_media boolean default null,p_ua text default '') returns bigint language plpgsql security definer set search_path='' as $$
declare pid bigint; p public.players; begin
 pid=public.my_player_id();
 if pid is null then raise exception 'Register first — there is no player record for this sign-in' using errcode='42501'; end if;
 select * into p from public.players where id=pid;
 if exists(select 1 from public.waiver_acceptances where player_id=pid and waiver_version=p_version) then raise exception 'You have already accepted waiver version %',p_version using errcode='22023'; end if;
 return public.record_waiver_acceptance(pid,coalesce(public.my_email(),p.email),p.name,p_version,p_sha,p_sig,p_tz,p_offset,'updated-version',p_age,p_minor,p_media,p_ua);
end $$;
revoke all on function public.accept_waiver(text,text,text,text,int,text,text,boolean,text) from public,anon;
grant execute on function public.accept_waiver(text,text,text,text,int,text,text,boolean,text) to authenticated;

-- The organizer chooses which version new sign-ups see; the others stay readable in the records.
create or replace function public.publish_waiver_version(p_version text) returns void language plpgsql security definer set search_path='' as $$ begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501'; end if;
 if not exists(select 1 from public.waiver_versions where version=p_version) then raise exception 'No waiver version %',p_version using errcode='22023'; end if;
 update public.waiver_versions set is_current=false where is_current and version<>p_version;
 update public.waiver_versions set is_current=true where version=p_version and not is_current;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'waiver.published',p_version,'{{}}'::jsonb);
end $$;
revoke all on function public.publish_waiver_version(text) from public,anon;
grant execute on function public.publish_waiver_version(text) to authenticated;

insert into public.waiver_versions(version,title,body,is_current,note) values
{ins}
on conflict(version) do nothing;
commit;
select version,is_current,sha256,length(body) as characters from public.waiver_versions order by version;
"""
out = ROOT / "legacy/migrations/L20_waiver_records.sql"
out.write_text(sql)
print(f"wrote {out.relative_to(ROOT)} ({len(sql.splitlines())} lines; versions: {', '.join(v for v, *_ in VERSIONS)})")
