#!/usr/bin/env python3
# Builds legacy/migrations/ROLLBACK_2026-09-12.sql, the database half of rolling back the September 2026 release.
# The functions production runs today are copied from the migrations that wrote them, never retyped:
#   register_me with 7 arguments — L10 (L20 replaces it with the 16-argument version that records the waiver);
#   save_court_scores            — L15 (L19 adds the best-of-three check).
# Prints the md5 of each function body; docs/28 section 9 uses them for the read-only check before the release.
#   python3 legacy/scripts/build-rollback-sql.py
import hashlib, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
mig = root / "legacy/migrations"

def block(file, start, end="end $$;"):
    s = (mig / file).read_text()
    assert s.count(start) == 1, (file, start)
    i = s.index(start)
    return s[i:s.index(end, i) + len(end)]

def md5_body(fn):
    # Postgres keeps the text between the dollar quotes exactly (pg_proc.prosrc).
    return hashlib.md5(fn[fn.index("$$") + 2:fn.rindex("$$")].encode()).hexdigest()

reg = block("L10_payment_declaration_and_vote_lock.sql", "create or replace function public.register_me(")
scs = block("L15_hardening.sql", "create or replace function public.save_court_scores(")
reg19, scs19 = (md5_body(block(f, s)) for f, s in (("L20_waiver_records.sql", "create or replace function public.register_me("),
                                                   ("L19_best_of_three.sql", "create or replace function public.save_court_scores(")))
R7, R16 = "public.register_me(text,text,text,text,text,text,text)", "public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text)"
S = "public.save_court_scores(int,int,jsonb,int)"
out = f"""-- ROLLBACK for the September 2026 release (L19, L20). Generated by legacy/scripts/build-rollback-sql.py; do not edit.
-- PREPARED ONLY. Run it together with putting the previous site back, and on production only with the organizer's
-- approval (docs/28 section 9). The previous site registers through the 7-argument register_me, which L20 removed.
-- What it does:
--   1. register_me: removes L20's 16-argument version and restores the 7-argument version exactly as L10 wrote it. The
--      two can't exist together: the new one's extra arguments have defaults, so a 7-argument call would be ambiguous.
--   2. save_court_scores: restores L15's version (without L19's best-of-three check).
-- What it keeps: the environment marker, the waiver wording, every acceptance record (records are never deleted) and
-- L21's privileges. Registrations through the previous site have no acceptance record.
-- It changes nothing unless the database has exactly this release's versions of both functions.
begin;
do $$ begin
 if to_regprocedure('{R16}') is null or (select md5(prosrc) from pg_proc where oid=to_regprocedure('{R16}'))<>'{reg19}'
 then raise exception 'register_me is not the version from this release (L20) — nothing was changed'; end if;
 if (select md5(prosrc) from pg_proc where oid=to_regprocedure('{S}'))<>'{scs19}'
 then raise exception 'save_court_scores is not the version from this release (L19) — nothing was changed'; end if;
end $$;
drop function {R16};
{reg}
revoke all on function {R7} from public,anon;
grant execute on function {R7} to authenticated;
{scs}
update public.environment set schema_version=schema_version||' (L19/L20 functions rolled back)';
end;
select 'register_me (7 arguments, L10)' as check_name, case when md5(prosrc)='{md5_body(reg)}' then 'OK' else 'FAIL' end as result from pg_proc where oid=to_regprocedure('{R7}')
union all select 'register_me (16 arguments) removed', case when to_regprocedure('{R16}') is null then 'OK' else 'FAIL' end
union all select 'save_court_scores (L15)', case when md5(prosrc)='{md5_body(scs)}' then 'OK' else 'FAIL' end from pg_proc where oid=to_regprocedure('{S}')
union all select 'waiver records kept', count(*)::text||' records' from public.waiver_acceptances;
"""
(mig / "ROLLBACK_2026-09-12.sql").write_text(out)
print(f"wrote legacy/migrations/ROLLBACK_2026-09-12.sql")
print(f"  register_me 7 arguments (L10)  md5 {md5_body(reg)}")
print(f"  save_court_scores (L15)        md5 {md5_body(scs)}")
print(f"  register_me 16 arguments (L20) md5 {reg19}")
print(f"  save_court_scores (L19)        md5 {scs19}")
