#!/bin/sh
# Assembles the production migration from the reviewed pieces (no synthetic-player step L02).
set -eu
cd "$(dirname "$0")/../.."
out=legacy/migrations/PROD_2026-27.sql
{
  echo "-- Maplewood league production migration, 2026-27. Generated by legacy/scripts/build-prod-migration.sh."
  echo "-- Run in the Supabase SQL editor of the PRODUCTION project, in one go, AFTER the verified backup (docs/20)."
  echo "-- Contents: L01 auth+rules, L03 scores+season, L04 backfill, L05 rollover, L06 statistics, L07 reminders+spares, L08 payments+push, L09 invitations, L10 payment declaration + 48-hour voting lock."
  for f in L01_auth_and_rules L03_scores_and_season L04_backfill_columns L05_rollover_registration L06_stats_rebuild L07_reminders_and_spares L08_payments_and_push L09_invites L10_payment_declaration_and_vote_lock; do
    echo; echo "-- ═══════════ $f ═══════════"; cat "legacy/migrations/$f.sql"
  done
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
