#!/usr/bin/env python3
"""Copy a production backup into the TEST database, so TEST holds the same league as production.

    python3 legacy/scripts/copy-production-into-test.py <backup.json> > /tmp/into-test.sql
    # then run /tmp/into-test.sql in the TEST project's SQL editor

TEST ONLY, and it proves it three ways:
  * the SQL calls public.assert_test_environment() first, so it refuses to run on production;
  * every player email becomes player-<id>@example.invalid, except the organizer's own address, which is kept so they
    can sign in to TEST as themselves. Nothing else that looks like a real address is ever emitted;
  * phone, emergency contact and medical notes are replaced with placeholders — the players' own details are not
    league behaviour, and a test database is not the place for them. Whether a field was filled in is preserved.
Names, courts, wins, losses, games, membership, approval, the live session, RSVPs, payments and the calendar are
copied exactly, because those are what the app's behaviour depends on.
Before it changes anything it copies TEST's current players into app_state under snapshot_test_players_<date>.
"""
import json, sys, pathlib, datetime, re

ORGANIZER = "christygeorge993@gmail.com"
if len(sys.argv) < 2: sys.exit("usage: copy-production-into-test.py <backup.json>")
d = json.loads(pathlib.Path(sys.argv[1]).read_text())
t = d["tables"]

def lit(v):
    if v is None: return "null"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def mask_email(p):
    e = (p.get("email") or "").strip().lower()
    return e if e == ORGANIZER else f"player-{p['id']}@example.invalid"

emails = [mask_email(p) for p in t["players"]]
for e in emails:
    if e != ORGANIZER and not e.endswith("@example.invalid"):
        sys.exit(f"refusing: {e} is neither the organizer's address nor a reserved test address")

stamp = datetime.date.today().strftime("%Y%m%d")
cols = ["id","name","email","phone","emergency","medical","sig","waiver_signed","paid","current_court","highest_court",
        "season_wins","season_losses","games_played","no_show_count","membership_type","approved","waitlisted",
        "admin_note","declared_payment","email_reminders","legacy_paid","registered_at","archived_at"]
out = [f"-- The production league of {d.get('exported_at','(unknown date)')} copied into TEST: {len(t['players'])} players,",
       "-- their own details replaced, every address reserved except the organizer's. Generated by",
       "-- legacy/scripts/copy-production-into-test.py. TEST ONLY.",
       "begin;",
       "select public.assert_test_environment();",
       f"delete from public.app_state where key='snapshot_test_players_{stamp}';",
       f"insert into public.app_state(key,value) select 'snapshot_test_players_{stamp}', "
       "coalesce(jsonb_agg(to_jsonb(p) order by p.id),'[]'::jsonb)::text from public.players p;",
       "delete from public.undo_journal; delete from public.rsvp_log; delete from public.rsvps; delete from public.payments;",
       "delete from public.push_subscriptions; delete from public.reminder_log; delete from public.questions;",
       "delete from public.invitations; delete from public.players; delete from public.season_dates;",
       "delete from public.app_state where key in ('current_session','completed_sessions','round_snapshots',"
       "'player_approvals','membership_overrides','pre_session_attendance','reminder_request','reminder_last_run',"
       "'vote_digest_last_id','season_config');"]

for p in t["players"]:
    row = dict(p)
    row["email"] = mask_email(p)
    row["phone"] = "613-555-0100" if (p.get("phone") or "").strip() else ""
    row["emergency"] = "Emergency contact (copied)" if (p.get("emergency") or "").strip() else ""
    row["medical"] = "Medical note (copied)" if (p.get("medical") or "").strip() else ""
    row["sig"] = "copied" if (p.get("sig") or "").strip() else ""
    row["user_id"] = None                      # TEST has its own sign-ins; the organizer claims their row by email
    # players.id is a generated identity column: keeping production's ids needs "overriding system value".
    out.append("insert into public.players(" + ",".join(cols) + ") overriding system value values(" + ",".join(lit(row.get(c)) for c in cols) + ");")
out.append(f"select setval(pg_get_serial_sequence('public.players','id'), (select coalesce(max(id),1) from public.players));")

for r in t.get("season_dates", []):
    out.append("insert into public.season_dates(session_number,play_on,start_at) values("
               f"{lit(r['session_number'])},{lit(r['play_on'])},{lit(r['start_at'])});")
for r in t.get("rsvps", []):
    out.append("insert into public.rsvps(session_number,player_id,response,note,updated_at) values("
               f"{lit(r['session_number'])},{lit(r['player_id'])},{lit(r['response'])},{lit(r.get('note',''))},{lit(r.get('updated_at'))});")
for r in t.get("payments", []):
    out.append("insert into public.payments(id,player_id,kind,amount,session_number,method,received_on,note,created_at) overriding system value values("
               f"{lit(r.get('id'))},{lit(r['player_id'])},{lit(r['kind'])},{lit(r['amount'])},{lit(r.get('session_number'))},"
               f"{lit(r.get('method'))},{lit(r.get('received_on'))},{lit(r.get('note'))},{lit(r.get('created_at'))});")
if t.get("payments"):
    out.append("select setval(pg_get_serial_sequence('public.payments','id'), (select coalesce(max(id),1) from public.payments));")

keep = {"current_session","completed_sessions","player_approvals","membership_overrides","pre_session_attendance","season_config"}
for r in t.get("app_state", []):
    if r["key"] in keep and r.get("value") is not None:
        out.append(f"insert into public.app_state(key,value,version) values({lit(r['key'])},{lit(r['value'])},{lit(r.get('version',1))});")

out += ["commit;",
        "select 'players' as table, count(*)::text as rows from public.players",
        "union all select 'reserved or organizer addresses only', case when count(*)=0 then 'OK' else 'FAIL: '||count(*) end "
        "from public.players where email not like '%@example.invalid' and email <> " + lit(ORGANIZER),
        "union all select 'season_dates', count(*)::text from public.season_dates",
        "union all select 'rsvps', count(*)::text from public.rsvps",
        "union all select 'payments', count(*)::text from public.payments",
        "union all select 'session', coalesce((select 'round '||(value::jsonb->>'cycle')||', completed='||(value::jsonb->>'completed')||"
        "', scores='||(select count(*) from jsonb_object_keys(value::jsonb->'scores')) from public.app_state where key='current_session'),'none');"]
print("\n".join(out))
