-- L16: TEST and production identical (September 11, 2026). Safe to run again.
-- 1. The three original tables get production's exact layout on any project (TEST was set up differently):
--    players: no default for the text fields, courts default 3, no_show_count and membership_type never empty, ids
--    generated by the database (identity); announcements: type/title/body, which the site writes (TEST still had an old
--    content column, so posting an announcement on TEST failed); app_state: keyed by key, no id column.
-- 2. undo_last is defined once more exactly as in L13, so both projects hold the same text.
-- 3. The job key (service_role) may run exactly the two functions the jobs call. Supabase's defaults had let it run
--    every function on production.
-- On production only step 3 changes anything.
begin;
alter table public.players alter column email drop default, alter column phone drop default, alter column emergency drop default,
  alter column medical drop default, alter column sig drop default, alter column current_court set default 3, alter column highest_court set default 3;
update public.players set no_show_count=0 where no_show_count is null;
update public.players set membership_type='regular' where membership_type is null;
alter table public.players alter column no_show_count set not null, alter column membership_type set not null;
alter table public.announcements add column if not exists type text default 'info', add column if not exists title text, add column if not exists body text;
do $$ begin
 if exists(select 1 from information_schema.columns where table_schema='public' and table_name='announcements' and column_name='content') then
  update public.announcements set body=coalesce(body,content) where true;
  alter table public.announcements drop column content;
 end if;
 if exists(select 1 from information_schema.columns where table_schema='public' and table_name='app_state' and column_name='id') then
  alter table public.app_state drop constraint if exists app_state_pkey;
  alter table public.app_state drop constraint if exists app_state_key_key;
  alter table public.app_state drop column id;
  alter table public.app_state add constraint app_state_pkey primary key (key);
 end if;
end $$;
alter table public.app_state alter column updated_at drop not null;
do $$ declare t text; m bigint; begin
 foreach t in array array['players','announcements'] loop
  if exists(select 1 from information_schema.columns where table_schema='public' and table_name=t and column_name='id' and column_default like 'nextval(%') then
   execute format('select coalesce(max(id),0)+1 from public.%I',t) into m;
   execute format('alter table public.%I alter column id drop default',t);
   execute format('drop sequence if exists public.%I',t||'_id_seq');
   execute format('alter table public.%I alter column id add generated always as identity (start with %s)',t,m);
  end if;
 end loop;
end $$;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.undo_last() returns jsonb language plpgsql security definer set search_path='' as $$
declare e public.undo_journal; k text; st jsonb;
begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501'; end if;
 perform 1 from public.app_state where key in ('current_session','completed_sessions','player_approvals','membership_overrides','pre_session_attendance') for update;
 select * into e from public.undo_journal order by id desc limit 1 for update;
 if e.id is null then raise exception 'Nothing to undo'; end if;
 if exists(select 1 from public.audit_log a where a.action='season.started' and a.created_at>e.created_at) then
  raise exception 'Nothing to undo since the new season started';
 end if;
 if e.snapshot=public.capture_state() then -- that step changed nothing (e.g. a dialog was cancelled): drop it, undo nothing else
  delete from public.undo_journal where id=e.id;
  return jsonb_build_object('undone',null,'skipped',e.label,'taken_at',e.created_at,'remaining',(select count(*) from public.undo_journal));
 end if;
 st=e.snapshot->'app_state';
 foreach k in array array['current_session','completed_sessions','player_approvals','membership_overrides','pre_session_attendance'] loop
  if st ? k then
   insert into public.app_state(key,value,version,updated_at) values(k,st->>k,1,now())
   on conflict(key) do update set value=excluded.value,version=public.app_state.version+1,updated_at=now();
  else
   delete from public.app_state where key=k;
  end if;
 end loop;
 update public.players p set current_court=(x->>'current_court')::int,highest_court=(x->>'highest_court')::int,no_show_count=(x->>'no_show_count')::int,
   approved=(x->>'approved')::boolean,waitlisted=(x->>'waitlisted')::boolean,membership_type=x->>'membership_type',
   season_wins=(x->>'season_wins')::int,season_losses=(x->>'season_losses')::int,games_played=(x->>'games_played')::int,updated_at=now()
 from jsonb_array_elements(e.snapshot->'players') x where p.id=(x->>'id')::bigint;
 delete from public.undo_journal where id=e.id;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'undo',e.label,jsonb_build_object('journal_id',e.id,'taken_at',e.created_at));
 return jsonb_build_object('undone',e.label,'taken_at',e.created_at,'remaining',(select count(*) from public.undo_journal));
end $$;

revoke execute on all functions in schema public from service_role;
grant execute on function public.dispatch_reminder_job(text), public.reminder_targets(int) to service_role;
commit;
