-- L20: waiver wording versions, and an acceptance record for every agreement. GENERATED by
-- legacy/scripts/build-waiver-records.py from legacy/waiver/*.txt — change those files, then rebuild.
--   waiver_versions     every wording ever shown, kept permanently; the database computes each one's SHA-256 and
--                       refuses any change to the wording (publish a new version instead). One is current.
--   waiver_acceptances  who accepted which version, when (UTC, plus the device's time zone), how (the registration
--                       form or a later acceptance of an updated version), the typed signature, adult or guardian,
--                       and the separate photo/video choice (empty when the wording offered none). Never updated or deleted; if a player record is deleted
--                       the link is cleared and the record stays. Organizer reads all; a player reads only their own.
--   register_me         now also records the acceptance, and refuses wording that is not the current version or
--                       whose digest does not match what the page showed. accept_waiver records an updated version.
--   publish_waiver_version  the organizer switches which version new sign-ups see.
-- Older registrations are not given acceptance records: consent is never back-filled.
begin;
create table if not exists public.waiver_versions(
  version text primary key check (version ~ '^[0-9]{4}-[0-9]{2}-v[0-9]+$'),
  title text not null,
  body text not null,
  sha256 text not null default '',
  published_at timestamptz not null default now(),
  is_current boolean not null default false,
  note text not null default '');
create unique index if not exists waiver_versions_one_current on public.waiver_versions(is_current) where is_current;
alter table public.waiver_versions enable row level security;
revoke all on public.waiver_versions from public,anon,authenticated;
drop policy if exists "signed-in users read waiver wording" on public.waiver_versions;
create policy "signed-in users read waiver wording" on public.waiver_versions for select to authenticated using(true);
grant select on public.waiver_versions to authenticated,service_role;
create or replace function public.waiver_versions_guard() returns trigger language plpgsql set search_path='' as $$ begin
 if tg_op='DELETE' then raise exception 'Waiver versions are kept permanently' using errcode='42501'; end if;
 if tg_op='UPDATE' and (new.version<>old.version or new.title<>old.title or new.body<>old.body or new.published_at<>old.published_at) then
  raise exception 'Waiver wording is never rewritten — publish a new version instead' using errcode='42501'; end if;
 new.sha256=encode(sha256(convert_to(new.body,'UTF8')),'hex');   -- always the database's own digest of the wording
 return new;
end $$;
drop trigger if exists waiver_versions_guard on public.waiver_versions;
create trigger waiver_versions_guard before insert or update or delete on public.waiver_versions for each row execute function public.waiver_versions_guard();

create table if not exists public.waiver_acceptances(
  id bigint generated always as identity primary key,
  player_id bigint references public.players(id) on delete set null,
  user_id uuid,
  email text not null,
  participant_name text not null,
  typed_signature text not null,
  waiver_version text not null references public.waiver_versions(version),
  waiver_sha256 text not null,
  accepted_at timestamptz not null default now(),
  client_timezone text not null default '',
  client_utc_offset_minutes int,
  action text not null check (action in ('registration','updated-version')),
  age_declaration text not null default 'adult' check (age_declaration in ('adult','guardian')),
  minor_name text not null default '',
  media_consent boolean,                              -- null: no separate photo/video choice was offered
  registration_ref text not null default '',
  user_agent text not null default '');
create index if not exists waiver_acceptances_player on public.waiver_acceptances(player_id);
create index if not exists waiver_acceptances_user on public.waiver_acceptances(user_id);
alter table public.waiver_acceptances enable row level security;
revoke all on public.waiver_acceptances from public,anon,authenticated;
drop policy if exists "organizer reads all acceptances, a player their own" on public.waiver_acceptances;
create policy "organizer reads all acceptances, a player their own" on public.waiver_acceptances for select to authenticated using(public.is_admin() or user_id=auth.uid());
grant select on public.waiver_acceptances to authenticated,service_role;
create or replace function public.waiver_acceptances_guard() returns trigger language plpgsql set search_path='' as $$ begin
 if tg_op='DELETE' then raise exception 'Waiver acceptance records are kept permanently' using errcode='42501'; end if;
 -- The only change allowed: the player record was deleted, so the link is cleared; the record itself stays as it was.
 if not (new.player_id is null and old.player_id is not null and (to_jsonb(new)-'player_id')=(to_jsonb(old)-'player_id')) then
  raise exception 'Waiver acceptance records are never changed' using errcode='42501'; end if;
 return new;
end $$;
drop trigger if exists waiver_acceptances_guard on public.waiver_acceptances;
create trigger waiver_acceptances_guard before update or delete on public.waiver_acceptances for each row execute function public.waiver_acceptances_guard();

-- Records one acceptance after checking it names the current wording exactly. Called only by the two functions below.
create or replace function public.record_waiver_acceptance(p_player bigint,p_email text,p_name text,p_version text,p_sha text,p_sig text,p_tz text,p_offset int,p_action text,p_age text,p_minor text,p_media boolean,p_ua text) returns bigint language plpgsql security definer set search_path='' as $$
declare wv public.waiver_versions; i bigint; begin
 select * into wv from public.waiver_versions where version=coalesce(p_version,'');
 if wv.version is null then raise exception 'The waiver on your screen is out of date — reload the page and read the current version' using errcode='22023'; end if;
 if not wv.is_current then raise exception 'The waiver was updated while you were registering — reload the page and read the current version' using errcode='22023'; end if;
 if lower(coalesce(p_sha,''))<>wv.sha256 then raise exception 'The waiver text on your screen does not match version % — reload the page and try again',wv.version using errcode='22023'; end if;
 if length(trim(coalesce(p_sig,''))) not between 2 and 80 then raise exception 'Type your full name to sign the waiver' using errcode='22023'; end if;
 if coalesce(p_age,'adult') not in ('adult','guardian') then raise exception 'Choose whether you are 18 or older or a parent or guardian' using errcode='22023'; end if;
 if p_age='guardian' and length(trim(coalesce(p_minor,''))) not between 2 and 80 then raise exception 'Enter the name of the participant under 18' using errcode='22023'; end if;
 insert into public.waiver_acceptances(player_id,user_id,email,participant_name,typed_signature,waiver_version,waiver_sha256,client_timezone,client_utc_offset_minutes,action,age_declaration,minor_name,media_consent,registration_ref,user_agent)
 values(p_player,auth.uid(),coalesce(p_email,''),trim(p_name),trim(p_sig),wv.version,wv.sha256,left(coalesce(p_tz,''),64),case when p_offset between -840 and 840 then p_offset end,p_action,coalesce(p_age,'adult'),
        case when p_age='guardian' then left(trim(p_minor),80) else '' end,p_media,'REG-'||coalesce(p_player::text,'?')||'-'||to_char(now() at time zone 'UTC','YYYYMMDD"T"HH24MISS"Z"'),left(coalesce(p_ua,''),300))
 returning id into i;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'waiver.accepted',coalesce(p_player::text,''),jsonb_build_object('version',wv.version,'action',p_action,'acceptance',i));
 return i;
end $$;
revoke all on function public.record_waiver_acceptance(bigint,text,text,text,text,text,text,int,text,text,text,boolean,text) from public,anon,authenticated;

drop function if exists public.register_me(text,text,text,text,text,text,text);
create or replace function public.register_me(p_name text,p_phone text,p_emergency text,p_medical text,p_sig text,p_membership text,p_payment text default '',
  p_waiver_version text default '',p_waiver_sha text default '',p_waiver_sig text default '',p_tz text default '',p_offset int default null,p_age text default 'adult',p_minor text default '',p_media boolean default null,p_ua text default '')
returns bigint language plpgsql security definer set search_path='' as $$ declare em text; inv public.invitations; existing public.players; pid bigint; pay text; begin
 select lower(trim(email)) into em from auth.users where id=auth.uid() and email_confirmed_at is not null;
 if em is null then raise exception 'Verified sign-in email required' using errcode='42501';end if;
 select * into inv from public.invitations where email=em;
 select * into existing from public.players where user_id=auth.uid() or (user_id is null and lower(email)=em) order by user_id is not null desc limit 1;
 if existing.id is null and inv.email is null and not public.is_admin_any_factor() then raise exception 'Registration is closed. This link is for players Christy has confirmed; contact the organizer if you were accepted.' using errcode='42501';end if;
 if p_name is null or length(trim(p_name)) not between 2 and 80 or coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 or coalesce(length(p_sig),0)>200000 then raise exception 'Invalid registration details';end if;
 pay=case when p_payment in ('paid_full','will_pay','per_session') then p_payment else '' end;
 if existing.id is null then
  insert into public.players(name,email,phone,emergency,medical,sig,waiver_signed,paid,current_court,highest_court,season_wins,season_losses,games_played,membership_type,approved,waitlisted,registered_at,user_id,declared_payment)
  values(trim(p_name),em,coalesce(p_phone,''),coalesce(p_emergency,''),coalesce(p_medical,''),coalesce(p_sig,''),p_sig is not null and p_sig<>'',false,0,0,0,0,0,coalesce(inv.membership_type,p_membership,'regular'),false,false,now(),auth.uid(),pay) returning id into pid;
 else
  update public.players set name=trim(p_name),phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),sig=case when p_sig is not null and p_sig<>'' then p_sig else sig end,waiver_signed=(p_sig is not null and p_sig<>'') or waiver_signed,membership_type=coalesce(inv.membership_type,membership_type),registered_at=now(),user_id=auth.uid(),declared_payment=case when pay<>'' then pay else declared_payment end,updated_at=now() where id=existing.id returning id into pid;
 end if;
 perform public.record_waiver_acceptance(pid,em,p_name,p_waiver_version,p_waiver_sha,p_waiver_sig,p_tz,p_offset,'registration',p_age,p_minor,p_media,p_ua);
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'player.registered',pid::text,jsonb_build_object('payment',pay,'waiver',p_waiver_version));
 return pid;
end $$;
revoke all on function public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text) from public,anon;
grant execute on function public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text) to authenticated;

-- A registered player accepts a newer version (once per version).
create or replace function public.accept_waiver(p_version text,p_sha text,p_sig text,p_tz text default '',p_offset int default null,p_age text default 'adult',p_minor text default '',p_media boolean default null,p_ua text default '') returns bigint language plpgsql security definer set search_path='' as $$
declare pid bigint; p public.players; begin
 pid=public.my_player_id();
 if pid is null then raise exception 'Register first — there is no player record for this sign-in' using errcode='42501'; end if;
 select * into p from public.players where id=pid;
 if exists(select 1 from public.waiver_acceptances where player_id=pid and waiver_version=p_version) then raise exception 'You have already accepted waiver version %',p_version using errcode='22023'; end if;
 return public.record_waiver_acceptance(pid,coalesce(public.my_email(),p.email),p.name,p_version,p_sha,p_sig,p_tz,p_offset,'updated-version',p_age,p_minor,p_media,p_ua);
end $$;
revoke all on function public.accept_waiver(text,text,text,text,int,text,text,boolean,text) from public,anon;
grant execute on function public.accept_waiver(text,text,text,text,int,text,text,boolean,text) to authenticated;

-- The organizer chooses which version new sign-ups see; the others stay readable in the records.
create or replace function public.publish_waiver_version(p_version text) returns void language plpgsql security definer set search_path='' as $$ begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501'; end if;
 if not exists(select 1 from public.waiver_versions where version=p_version) then raise exception 'No waiver version %',p_version using errcode='22023'; end if;
 update public.waiver_versions set is_current=false where is_current and version<>p_version;
 update public.waiver_versions set is_current=true where version=p_version and not is_current;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'waiver.published',p_version,'{}'::jsonb);
end $$;
revoke all on function public.publish_waiver_version(text) from public,anon;
grant execute on function public.publish_waiver_version(text) to authenticated;

insert into public.waiver_versions(version,title,body,is_current,note) values
  ('2026-09-v1','Liability Waiver, Activity Release and Payment Policy',$wv$# DC Badminton Club — Maplewood Ladder League
Privately organized recreational badminton group operated by Christy George (individual organizer) — not a registered corporation or non-profit
700 Cope Drive, Stittsville · Tuesdays 8:00–10:00 PM · Sep 15, 2026 – May 18, 2027

## 1. Nature of the Activity & Group

DC Badminton Club is a privately organized recreational badminton group. It is not a registered corporation, non-profit, or incorporated association. All sessions are organized by Christy George (individual). By registering, I understand and accept this context and voluntarily choose to participate.

## 2. Assumption of Risk

I understand that participating in badminton involves inherent risks of physical injury including but not limited to muscle strains, sprains, falls, collisions, and eye injuries. I voluntarily and knowingly assume full responsibility for all risks, injuries, or damages that may occur as a result of my participation in DC Badminton Club activities.

## 3. Release of Liability

I hereby release, waive, and discharge Christy George (individual organizer), any co-organizers, volunteers operating under the DC Badminton Club name, and OCDSB (Ottawa-Carleton District School Board) from any and all claims, liabilities, expenses, or legal actions arising from ordinary negligence related to injuries, losses, or damages incurred during participation. Note: Ontario law does not permit waivers for gross negligence or intentional misconduct — this release covers ordinary negligence only.

## 4. Physical Condition & Medical

I certify that I am in good physical condition and have no medical conditions that prevent me from safely participating in badminton. If I have medical concerns, I have consulted a physician and obtained clearance. I agree to notify the organizer immediately of any discomfort, pain, or medical issues that arise during participation. DC Badminton Club is not responsible for medical or emergency costs arising from my participation.

## 5. Age Requirement

This league is open to all ages. Participants under 18 must have a parent or legal guardian register on their behalf and sign this waiver. By registering, I confirm that I am either 18 years of age or older, or that I am a parent/legal guardian registering and accepting responsibility for a minor participant.

## 6. OCDSB Facility Rules

• Non-marking, soft-soled indoor shoes are mandatory at all times
• No food or drinks in the gymnasium
• No alcohol, smoking, vaping or cannabis on school premises
• Play 8:00–10:00 PM; finish play by 10:05 PM and leave by 10:15 PM sharp
• Remain in designated gymnasium areas only
• No nuts, nut products, shellfish or latex items on premises
• No aggressive behaviour, coarse language, or discrimination of any kind
• Only custodians may adjust mechanical or building equipment

## 7. Personal Belongings

DC Badminton Club and OCDSB are not responsible for lost, stolen, or damaged personal belongings while at the facility. Players are responsible for their own equipment and valuables. Leave valuables at home.

## 8. Strict Non-Refundable Payment Policy (No Exceptions)

All fees paid to DC Badminton Club are final, non-negotiable, and non-refundable under any circumstances, including but not limited to: personal schedule conflicts, illness or injury, relocation, missed sessions, or cancellations due to bad weather, facility closures, or OCDSB/city-imposed shutdowns. Sessions will not be rescheduled or credited unless the organizer cancels for their own internal reasons. Registration is only confirmed upon receipt of full payment.

## 9. E-Transfer Payment

If paying by e-transfer, it is solely my responsibility to ensure payment is received and confirmed at christygeorge993@gmail.com. If an e-transfer is not received, not confirmed, or rejected, my registration will be considered incomplete and I will not be permitted to participate until resolved.

## 10. Media Consent

I grant permission to DC Badminton Club to use photographs or videos of me taken during sessions or events for promotional purposes including social media and the club website, at no compensation. To revoke this consent, I must submit a written request to the organizer.

## 11. Personal Information & Privacy

I consent to DC Badminton Club collecting and using my personal information (name, email, phone, emergency contact, and any medical notes) solely for the purpose of administering the league. This information will not be sold or shared with third parties. It will be retained for the duration of the league season and may be deleted upon request.

## 12. Consent & Agreement

By checking the boxes below and entering my digital signature, I confirm I have read, understood, and fully agree to all terms of this Liability Waiver, Activity Release, and Payment Policy. I understand this is a voluntary private recreational arrangement. This constitutes a binding digital agreement between me and Christy George (individual organizer).

## Acceptance
I have read and agree to all sections above including: liability waiver & release, assumption of risk, OCDSB facility rules, non-refundable payment policy, media consent, privacy policy, and e-transfer responsibility. If registering a minor, I accept full responsibility as parent/guardian.
⚠️ By typing your name you confirm this is a legally binding digital signature$wv$,true,'The wording on the 2026-27 sign-up form before acceptance records began (as committed in aebbc28 and shown on the league site). That form also required a separate payment acknowledgement box on this step ($400 for regulars, $20 per session for spares). No individual acceptance of this version was recorded.'),
  ('2026-09-v2','Release of Liability, Waiver of Claims, Assumption of Risk and Consent',$wv$# DC Badminton Club — Maplewood Ladder League
Release of Liability, Waiver of Claims, Assumption of Risk and Consent · Version 2026-09-v2
Tuesdays 8:00–10:00 PM, September 15, 2026 – May 18, 2027 · Maplewood Secondary School, 700 Cope Drive, Stittsville, Ontario

PLEASE READ CAREFULLY — THIS AGREEMENT AFFECTS YOUR LEGAL RIGHTS. By accepting it you give up the right to sue the people and organizations named in section 3 for injury, loss or damage, including injury, loss or damage caused by their negligence. Do not accept it unless you have read and understood it. You may ask the Organizer questions, or get legal advice, before you accept.

## 1. Who runs the league
DC Badminton Club is a private recreational group organized by Christy George as an individual (the "Organizer"). It is not a corporation, a non-profit or an incorporated association. Play takes place in a gymnasium of the Ottawa-Carleton District School Board ("OCDSB") under a community-use permit.

## 2. The risks of badminton
Badminton involves sudden starts, stops, lunges, jumps and changes of direction, fast-moving shuttlecocks and swinging racquets, often with other players close by. Taking part carries a risk of injury, some of it serious or permanent, including:
• sprains, strains, and muscle, tendon or ligament tears (such as an Achilles tendon rupture), fractures, dislocations and joint injuries;
• eye and face injuries from a shuttlecock or racquet, which can cause permanent loss of sight;
• being hit by a racquet, a shuttlecock or another player, and collisions on the same or a neighbouring court;
• slips, trips and falls, including on the floor, court lines, moisture, bags or equipment;
• overexertion, dehydration, heat illness, and heart attack or other medical events brought on by exercise;
• harm arising from the conduct of other participants or from the condition of the facility or equipment.
These are examples, not a complete list. Some risks cannot be removed without changing the nature of the game.

## 3. Release and waiver of claims
In return for being allowed to take part, I release and give up all claims that I (or anyone claiming through me) may have against the Organizer, any volunteer who helps run the league, and OCDSB, and their employees and representatives (together, the "Releasees"), for personal injury, death, loss of or damage to property, or any other loss arising from my taking part in league activities, INCLUDING ANY INJURY, LOSS OR DAMAGE CAUSED BY THE NEGLIGENCE OF A RELEASEE. I agree not to start or continue any legal action against a Releasee for such a claim. This release does not cover gross negligence or deliberate wrongdoing, and it does not take away any right that Ontario law does not allow me to give up.

## 4. Assumption of risk
I understand the risks described in section 2, and that there may be others that cannot be foreseen. I freely choose to take part and I accept those risks.

## 5. My responsibilities
• I will warm up and play within my own fitness, health and skill.
• I will wear non-marking, soft-soled indoor court shoes, and I am strongly encouraged to wear protective eyewear.
• I will follow the league rules, the Organizer's directions and the OCDSB facility rules in section 7.
• I will look over my court and the area around it and tell the Organizer about any hazard, such as a wet floor, loose equipment or a damaged net, before or during play.
• I will stop playing and tell the Organizer if I feel unwell, dizzy, short of breath or injured.
• I will not take part while impaired by alcohol, cannabis or any drug.
• I will play fairly and with care for the safety of others.

## 6. Health, first aid and emergencies
I confirm that I know of no medical reason why I should not take part in vigorous exercise, or that a physician has cleared me to do so. There is no medical staff at the gym, and the Organizer and volunteers are not medical professionals. In an emergency, 9-1-1 will be called. I consent to reasonable first aid being given to me and to emergency medical services being called for me, and I understand that any cost of treatment or ambulance transport is my responsibility. The emergency contact I gave when registering may be called if I am injured or unwell. I will tell the Organizer, in confidence, about any medical condition that could affect my safety while playing.

## 7. OCDSB facility rules
• Non-marking, soft-soled indoor shoes are mandatory at all times
• No food or drinks in the gymnasium
• No alcohol, smoking, vaping or cannabis on school premises
• Play 8:00–10:00 PM; finish play by 10:05 PM and leave by 10:15 PM sharp
• Remain in designated gymnasium areas only
• No nuts, nut products, shellfish or latex items on premises
• No aggressive behaviour, coarse language, or discrimination of any kind
• Only custodians may adjust mechanical or building equipment

## 8. Personal belongings
The Releasees are not responsible for lost, stolen or damaged personal belongings. I am responsible for my own equipment and valuables, and I will leave valuables at home.

## 9. Fees and refunds
My fee is shown on the registration form and is paid by e-transfer to christygeorge993@gmail.com. It is my responsibility to make sure the e-transfer is received; my registration is not complete until the Organizer confirms payment. Fees are not refunded for missed sessions, illness, injury, schedule conflicts or relocation. The only exceptions are the ones in the league's season rules (the refund for declining a session in time, and the arrangements when the school cancels an approved date).

## 10. Photos and video (optional)
Consent to photos and video is separate and optional: I give it only by ticking its own box below. If I give it, the Organizer may use photos or video of me taken at league sessions to promote the league, including on social media, without payment. I can withdraw it at any time by telling the Organizer; withdrawal applies to future use. Not giving it does not affect my place in the league.

## 11. Personal information
I consent to the Organizer collecting and using my name, email address, phone number, emergency contact and any medical information I choose to give, to run the league, contact me and respond to emergencies. It is not sold or shared, except with emergency services when needed or where the law requires. A record of this agreement (its exact wording, my acceptance and the date and time) is kept even after I leave the league, for as long as a claim relating to my participation could be made. I may ask to see the information held about me and to have information that is no longer needed deleted.

## 12. Participants under 18
A person under 18 may take part only if a parent or legal guardian registers them and accepts this agreement. The parent or guardian confirms that they have explained the risks in section 2 to the participant, that the participant agrees to follow the rules in sections 5 and 7, and that they will arrange any supervision the Organizer asks for.

## 13. General
This agreement is governed by the laws of Ontario and the federal laws of Canada that apply there. If any part of it is found to be unenforceable, the rest continues to apply. My ticked box and typed name are my electronic signature and have the same effect as a signature on paper.

## Acceptance
I have read this agreement, I understand it, and I accept it voluntarily. I understand that by accepting it I am giving up legal rights, including the right to sue the Releasees for negligence.$wv$,false,'Revised draft after the Ontario review in docs/28. Have an Ontario lawyer review it before it becomes the current version on the league site.')
on conflict(version) do nothing;
commit;
select version,is_current,sha256,length(body) as characters from public.waiver_versions order by version;
