-- Maplewood league production migration, 2026-27. Generated by legacy/scripts/build-prod-migration.sh.
-- Run in the Supabase SQL editor of the PRODUCTION project, in one go, AFTER the verified backup (docs/20).
-- Contents: L01 auth+rules, L03 scores+season, L04 backfill, L05 rollover, L06 statistics, L07 reminders+spares, L08 payments+push.

-- ═══════════ L01_auth_and_rules ═══════════
-- Maplewood league site, Phase 1: sign-in, organizer role and row-level rules for the legacy tables.
-- Additive and idempotent. Safe for TEST now and for production at cutover (after a verified backup).
begin;

-- Columns the running app already reads/writes but the original setup never created.
alter table public.players add column if not exists approved boolean not null default true;
alter table public.players add column if not exists waitlisted boolean not null default false;
alter table public.players add column if not exists registered_at timestamptz;
alter table public.players add column if not exists admin_note text not null default '';
alter table public.players add column if not exists user_id uuid references auth.users(id);
alter table public.players add column if not exists updated_at timestamptz not null default now();
create index if not exists players_email_lower on public.players(lower(email));
alter table public.app_state add column if not exists version int not null default 0;
alter table public.app_state add column if not exists updated_at timestamptz not null default now();
create unique index if not exists app_state_key_unique on public.app_state(key);

-- Organizer accounts. A row here plus a second factor (aal2 in the token) is what "admin" means.
create table if not exists public.app_admins(user_id uuid primary key references auth.users(id) on delete cascade,label text not null default 'organizer',added_at timestamptz not null default now());

-- Closed registration: only these sign-in emails may complete onboarding.
create table if not exists public.invitations(email text primary key check(email=lower(trim(email)) and email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),membership_type text not null default 'regular' check(membership_type in ('regular','spare')),note text not null default '',created_at timestamptz not null default now());

-- Per-player records that used to be shared JSON blobs (lost updates, forgeable).
create table if not exists public.rsvps(session_number int not null,player_id bigint not null references public.players(id) on delete cascade,response text not null check(response in ('coming','notcoming','maybe','late','need_spare')),note text not null default '' check(length(note)<=300),updated_at timestamptz not null default now(),primary key(session_number,player_id));
create table if not exists public.questions(id bigint generated always as identity primary key,player_id bigint references public.players(id) on delete set null,asker text not null default '',question text not null check(length(question) between 1 and 1000),answer text,answered_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_log(id bigint generated always as identity primary key,actor uuid,action text not null,subject text,detail jsonb,created_at timestamptz not null default now());

create or replace function public.my_email() returns text language sql stable as $$ select lower(trim(coalesce(auth.jwt()->>'email',''))) $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$
 select coalesce(auth.jwt()->>'aal','')='aal2' and exists(select 1 from public.app_admins a where a.user_id=auth.uid())
$$;
create or replace function public.is_admin_any_factor() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.app_admins a where a.user_id=auth.uid())
$$;
create or replace function public.my_player_id() returns bigint language sql stable security definer set search_path='' as $$
 select p.id from public.players p where p.user_id=auth.uid() or (p.user_id is null and lower(p.email)=public.my_email()) order by p.user_id is not null desc,p.id limit 1
$$;

-- Replace every unconditional anonymous policy.
do $$ declare p record; begin
 for p in select tablename,policyname from pg_policies where schemaname='public' and tablename in ('players','announcements','app_state','rsvps','questions','invitations','app_admins','audit_log') loop
  execute format('drop policy if exists %I on public.%I',p.policyname,p.tablename);
 end loop;
end $$;
alter table public.players enable row level security;
alter table public.announcements enable row level security;
alter table public.app_state enable row level security;
alter table public.rsvps enable row level security;
alter table public.questions enable row level security;
alter table public.invitations enable row level security;
alter table public.app_admins enable row level security;
alter table public.audit_log enable row level security;

create policy players_read on public.players for select to authenticated using(public.is_admin() or user_id=auth.uid() or (user_id is null and lower(email)=public.my_email()));
create policy players_admin_insert on public.players for insert to authenticated with check(public.is_admin());
create policy players_admin_update on public.players for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy players_admin_delete on public.players for delete to authenticated using(public.is_admin());
create policy announcements_read on public.announcements for select to authenticated using(true);
create policy announcements_admin_write on public.announcements for insert to authenticated with check(public.is_admin());
create policy announcements_admin_update on public.announcements for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy announcements_admin_delete on public.announcements for delete to authenticated using(public.is_admin());
-- Shared state is readable by signed-in members except private snapshots and retired secrets; only organizers write, and only through set_state().
create policy app_state_read on public.app_state for select to authenticated using(public.is_admin() or (key not like 'snapshot\_%' and key not in ('admin_pin','pin','invite_code')));
create policy rsvps_read on public.rsvps for select to authenticated using(true);
create policy rsvps_own_insert on public.rsvps for insert to authenticated with check(player_id=public.my_player_id());
create policy rsvps_own_update on public.rsvps for update to authenticated using(player_id=public.my_player_id() or public.is_admin()) with check(player_id=public.my_player_id() or public.is_admin());
create policy questions_read on public.questions for select to authenticated using(true);
create policy questions_own_insert on public.questions for insert to authenticated with check(player_id=public.my_player_id());
create policy questions_admin_update on public.questions for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy questions_admin_delete on public.questions for delete to authenticated using(public.is_admin());
create policy invitations_admin on public.invitations for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy app_admins_self on public.app_admins for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy audit_admin_read on public.audit_log for select to authenticated using(public.is_admin());

-- Public projection for standings, courts and rosters: no contact, emergency, medical or signature data.
create or replace view public.players_public as
 select id,name,paid,current_court,highest_court,season_wins,season_losses,games_played,no_show_count,membership_type,approved,waitlisted,registered_at,created_at,
 (waiver_signed is true or (sig is not null and sig<>'' and sig<>'admin')) as waiver_ok,(user_id is not null) as has_account
 from public.players;

-- Versioned shared-state writes: a stale screen cannot overwrite newer data.
create or replace function public.set_state(k text,v text,expected int) returns int language plpgsql security definer set search_path='' as $$ declare cur int;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if k is null or length(k) not between 1 and 120 or v is null or k like 'snapshot\_%' and length(v)>4000000 then raise exception 'Invalid state write';end if;
 if k in ('admin_pin','pin','invite_code') then raise exception 'Retired key';end if;
 select version into cur from public.app_state where key=k for update;
 if cur is null then
  if coalesce(expected,0)<>0 then raise exception 'Stale state: refresh before saving' using errcode='40001';end if;
  insert into public.app_state(key,value,version,updated_at) values(k,v,1,now());return 1;
 end if;
 if expected is null or expected<>cur then raise exception 'Stale state: refresh before saving' using errcode='40001';end if;
 update public.app_state set value=v,version=cur+1,updated_at=now() where key=k;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'state.set',k,jsonb_build_object('version',cur+1));
 return cur+1;
end $$;
create or replace function public.delete_state(k text) returns void language plpgsql security definer set search_path='' as $$ begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 delete from public.app_state where key=k;
 insert into public.audit_log(actor,action,subject) values(auth.uid(),'state.delete',k);
end $$;

-- Registration through the closed list: creates or claims the caller's own player row only.
create or replace function public.register_me(p_name text,p_phone text,p_emergency text,p_medical text,p_sig text,p_membership text) returns bigint language plpgsql security definer set search_path='' as $$ declare em text; inv public.invitations; existing public.players; pid bigint;begin
 select lower(trim(email)) into em from auth.users where id=auth.uid() and email_confirmed_at is not null;
 if em is null then raise exception 'Verified sign-in email required' using errcode='42501';end if;
 select * into inv from public.invitations where email=em;
 select * into existing from public.players where user_id=auth.uid() or (user_id is null and lower(email)=em) order by user_id is not null desc limit 1;
 if existing.id is null and inv.email is null then raise exception 'Registration is closed. This link is for players Christy has confirmed; contact the organizer if you were accepted.' using errcode='42501';end if;
 if p_name is null or length(trim(p_name)) not between 2 and 80 or coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 or coalesce(length(p_sig),0)>200000 then raise exception 'Invalid registration details';end if;
 if existing.id is null then
  insert into public.players(name,email,phone,emergency,medical,sig,waiver_signed,paid,current_court,highest_court,season_wins,season_losses,games_played,membership_type,approved,waitlisted,registered_at,user_id)
  values(trim(p_name),em,coalesce(p_phone,''),coalesce(p_emergency,''),coalesce(p_medical,''),coalesce(p_sig,''),p_sig is not null and p_sig<>'',false,0,0,0,0,0,coalesce(inv.membership_type,p_membership,'regular'),false,false,now(),auth.uid()) returning id into pid;
 else
  update public.players set name=trim(p_name),phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),sig=case when p_sig is not null and p_sig<>'' then p_sig else sig end,waiver_signed=waiver_signed or (p_sig is not null and p_sig<>''),registered_at=coalesce(registered_at,now()),user_id=auth.uid(),updated_at=now() where id=existing.id returning id into pid;
 end if;
 insert into public.audit_log(actor,action,subject) values(auth.uid(),'player.registered',pid::text);
 return pid;
end $$;
create or replace function public.update_my_profile(p_phone text,p_emergency text,p_medical text) returns void language plpgsql security definer set search_path='' as $$ declare pid bigint;begin
 pid=public.my_player_id();if pid is null then raise exception 'No player record' using errcode='42501';end if;
 if coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 then raise exception 'Invalid details';end if;
 update public.players set phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),user_id=coalesce(user_id,auth.uid()),updated_at=now() where id=pid;
end $$;
-- Own RSVP for the current session (upsert; admins may record on a player's behalf).
create or replace function public.set_rsvp(p_session int,p_player bigint,p_response text,p_note text default '') returns void language plpgsql security definer set search_path='' as $$ begin
 if p_player<>public.my_player_id() and not public.is_admin() then raise exception 'You can only answer for yourself' using errcode='42501';end if;
 if p_response not in ('coming','notcoming','maybe','late','need_spare') then raise exception 'Invalid response';end if;
 insert into public.rsvps(session_number,player_id,response,note) values(p_session,p_player,p_response,coalesce(p_note,''))
 on conflict(session_number,player_id) do update set response=excluded.response,note=excluded.note,updated_at=now();
end $$;
create or replace function public.admin_status() returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('organizer',public.is_admin_any_factor(),'verified',public.is_admin(),'player_id',public.my_player_id(),'email',public.my_email())
$$;

-- Grants: nothing for anonymous visitors; members get rule-limited access; organizers act through the same rules.
revoke all on all tables in schema public from anon;
revoke all on all functions in schema public from anon,public;
grant usage on schema public to authenticated;
grant select on public.players,public.announcements,public.app_state,public.rsvps,public.questions,public.invitations,public.app_admins,public.audit_log,public.players_public to authenticated;
grant insert,update,delete on public.players,public.announcements,public.questions,public.invitations to authenticated;
grant insert,update on public.rsvps to authenticated;
grant execute on function public.my_email(),public.is_admin(),public.is_admin_any_factor(),public.my_player_id(),public.set_state(text,text,int),public.delete_state(text),public.register_me(text,text,text,text,text,text),public.update_my_profile(text,text,text),public.set_rsvp(int,bigint,text,text),public.admin_status() to authenticated;
grant usage,select on all sequences in schema public to authenticated;
commit;

-- ═══════════ L03_scores_and_season ═══════════
-- Maplewood league site, Phase 2: court-scoped score entry for players, season rollover, re-registration.
begin;

-- Re-registering for a new season stamps a new registration date (drives "registered this season").
create or replace function public.register_me(p_name text,p_phone text,p_emergency text,p_medical text,p_sig text,p_membership text) returns bigint language plpgsql security definer set search_path='' as $$ declare em text; inv public.invitations; existing public.players; pid bigint;begin
 select lower(trim(email)) into em from auth.users where id=auth.uid() and email_confirmed_at is not null;
 if em is null then raise exception 'Verified sign-in email required' using errcode='42501';end if;
 select * into inv from public.invitations where email=em;
 select * into existing from public.players where user_id=auth.uid() or (user_id is null and lower(email)=em) order by user_id is not null desc limit 1;
 if existing.id is null and inv.email is null then raise exception 'Registration is closed. This link is for players Christy has confirmed; contact the organizer if you were accepted.' using errcode='42501';end if;
 if p_name is null or length(trim(p_name)) not between 2 and 80 or coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 or coalesce(length(p_sig),0)>200000 then raise exception 'Invalid registration details';end if;
 if existing.id is null then
  insert into public.players(name,email,phone,emergency,medical,sig,waiver_signed,paid,current_court,highest_court,season_wins,season_losses,games_played,membership_type,approved,waitlisted,registered_at,user_id)
  values(trim(p_name),em,coalesce(p_phone,''),coalesce(p_emergency,''),coalesce(p_medical,''),coalesce(p_sig,''),p_sig is not null and p_sig<>'',false,0,0,0,0,0,coalesce(inv.membership_type,p_membership,'regular'),false,false,now(),auth.uid()) returning id into pid;
 else
  update public.players set name=trim(p_name),phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),sig=case when p_sig is not null and p_sig<>'' then p_sig else sig end,waiver_signed=(p_sig is not null and p_sig<>'') or waiver_signed,membership_type=coalesce(inv.membership_type,membership_type),registered_at=now(),user_id=auth.uid(),updated_at=now() where id=existing.id returning id into pid;
 end if;
 insert into public.audit_log(actor,action,subject) values(auth.uid(),'player.registered',pid::text);
 return pid;
end $$;

-- Players on a court record that court's games for the current round; the organizer can record any court.
-- Each game must finish at the court's target (15 with five players, otherwise 21) with no tie.
create or replace function public.save_court_scores(p_court int,p_cycle int,p_scores jsonb,p_expected int) returns int language plpgsql security definer set search_path='' as $$
declare st public.app_state; cur jsonb; assigned jsonb; n int; target int; k text; sc jsonb; sa int; sb int; me bigint; cnt int=0;begin
 me=public.my_player_id();
 select * into st from public.app_state where key='current_session' for update;
 if st.key is null then raise exception 'No active session';end if;
 cur=st.value::jsonb;
 if p_expected is not null and p_expected<>st.version then raise exception 'Stale state: refresh before saving' using errcode='40001';end if;
 if coalesce((cur->>'cycle')::int,1)<>p_cycle then raise exception 'That round is over — refresh to see the current round' using errcode='40001';end if;
 if coalesce((cur->>'completed')::boolean,false) then raise exception 'Session is complete; scores are locked';end if;
 if p_court is null or p_court not between 1 and 6 then raise exception 'Invalid court';end if;
 assigned=coalesce(cur->'assignments'->(p_court::text),'[]'::jsonb);
 n=jsonb_array_length(assigned);
 if not public.is_admin() then
  if me is null or not exists(select 1 from jsonb_array_elements(assigned) e where (e#>>'{}')::bigint=me) then raise exception 'Only players on this court (or the organizer) can enter its scores' using errcode='42501';end if;
 end if;
 target=case when n=5 then 15 else 21 end;
 if jsonb_typeof(p_scores)<>'object' then raise exception 'Invalid scores';end if;
 for k,sc in select * from jsonb_each(p_scores) loop
  if k !~ ('^c'||p_court||'_y'||p_cycle||'_g[1-5]$') then raise exception 'Score key % is not on this court/round',k;end if;
  sa=(sc->>'sA')::int;sb=(sc->>'sB')::int;
  if sa is null or sb is null or sa<0 or sb<0 or sa=sb or greatest(sa,sb)<>target or least(sa,sb)>=target then raise exception 'Game % must finish at % with no tie',k,target;end if;
  if (sc->>'w') is distinct from (case when sa>sb then 'A' else 'B' end) then raise exception 'Winner flag does not match the score for %',k;end if;
  cur=jsonb_set(cur,array['scores',k],sc,true);cnt=cnt+1;
 end loop;
 if cnt=0 then raise exception 'No scores supplied';end if;
 update public.app_state set value=cur::text,version=version+1,updated_at=now() where key='current_session';
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'scores.saved','court '||p_court,jsonb_build_object('cycle',p_cycle,'games',cnt,'version',st.version+1));
 return st.version+1;
end $$;

-- Season rollover: archive the finished season, zero the season statistics and require fresh registration.
create or replace function public.start_new_season(p_label text) returns jsonb language plpgsql security definer set search_path='' as $$ declare archive jsonb; sessions text; cur text; n int;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if p_label is null or length(trim(p_label)) not between 3 and 40 or exists(select 1 from public.app_state where key='archive_'||trim(p_label)) then raise exception 'Unique archive label required';end if;
 select value into sessions from public.app_state where key='completed_sessions';
 select value into cur from public.app_state where key='current_session';
 if cur is not null then raise exception 'End the active session before starting a new season';end if;
 archive=jsonb_build_object('label',trim(p_label),'archived_at',now(),'completed_sessions',coalesce(sessions,'[]')::jsonb,
  'players',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'current_court',current_court,'highest_court',highest_court,'season_wins',season_wins,'season_losses',season_losses,'games_played',games_played,'no_show_count',no_show_count,'membership_type',membership_type) order by id),'[]'::jsonb) from public.players),
  'state',(select coalesce(jsonb_object_agg(key,value::jsonb),'{}'::jsonb) from public.app_state where key in ('player_approvals','membership_overrides','pre_session_attendance','round_snapshots') or key like 'votes_session_%' or key like 'rsvp_session_%'));
 insert into public.app_state(key,value,version,updated_at) values('archive_'||trim(p_label),archive::text,1,now());
 delete from public.app_state where key in ('completed_sessions','player_approvals','membership_overrides','pre_session_attendance','round_snapshots') or key like 'votes_session_%' or key like 'rsvp_session_%';
 delete from public.rsvps;
 update public.players set season_wins=0,season_losses=0,games_played=0,no_show_count=0,paid=false,approved=false,waitlisted=false,updated_at=now();
 get diagnostics n=row_count;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'season.started',trim(p_label),jsonb_build_object('players_reset',n));
 return jsonb_build_object('archived',trim(p_label),'players_reset',n);
end $$;
-- Archives are readable by members (results only, no contact details) so previous seasons can be shown.
create policy app_state_archive_read on public.app_state for select to authenticated using(key like 'archive\_%');
revoke all on function public.save_court_scores(int,int,jsonb,int),public.start_new_season(text) from public,anon;
grant execute on function public.save_court_scores(int,int,jsonb,int),public.start_new_season(text) to authenticated;
commit;

-- ═══════════ L04_backfill_columns ═══════════
-- Backfill approval, waitlist, registration date and membership type from the legacy JSON blobs into columns.
-- Idempotent; safe on TEST now and on production at cutover (run after L01).
begin;
with pa as (
 select (e.key)::bigint as id,e.value as v from public.app_state s cross join lateral jsonb_each(s.value::jsonb) e where s.key='player_approvals'
)
update public.players p set
 approved=coalesce((pa.v->>'approved')::boolean,p.approved),
 waitlisted=coalesce((pa.v->>'waitlisted')::boolean,p.waitlisted),
 membership_type=coalesce(nullif(pa.v->>'membershipType',''),p.membership_type),
 registered_at=coalesce(p.registered_at,nullif(pa.v->>'registeredAt','')::timestamptz),
 updated_at=now()
from pa where pa.id=p.id;
with mo as (
 select (e.key)::bigint as id,e.value as v from public.app_state s cross join lateral jsonb_each_text(s.value::jsonb) e where s.key='membership_overrides'
)
update public.players p set membership_type=mo.v,updated_at=now() from mo where mo.id=p.id and mo.v in ('regular','spare') and p.membership_type is distinct from mo.v;
update public.players set membership_type='regular' where membership_type is null or membership_type not in ('regular','spare');
-- Players never marked in the blob keep the column default (approved) only if they have played or hold a court; others start unapproved.
update public.players p set approved=false where approved and current_court=0 and games_played=0 and not exists(select 1 from public.app_state s where s.key='player_approvals' and (s.value::jsonb ? p.id::text));
commit;
select count(*) filter(where approved) approved,count(*) filter(where waitlisted) waitlisted,count(*) filter(where membership_type='spare') spares,count(*) filter(where registered_at is not null) dated from public.players;

-- ═══════════ L05_rollover_registration ═══════════
-- Rollover must withdraw last season's registration date so every player registers afresh, whatever the calendar date.
begin;
create or replace function public.start_new_season(p_label text) returns jsonb language plpgsql security definer set search_path='' as $$ declare archive jsonb; sessions text; cur text; n int;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if p_label is null or length(trim(p_label)) not between 3 and 40 or exists(select 1 from public.app_state where key='archive_'||trim(p_label)) then raise exception 'Unique archive label required';end if;
 select value into sessions from public.app_state where key='completed_sessions';
 select value into cur from public.app_state where key='current_session';
 if cur is not null then raise exception 'End the active session before starting a new season';end if;
 archive=jsonb_build_object('label',trim(p_label),'archived_at',now(),'completed_sessions',coalesce(sessions,'[]')::jsonb,
  'players',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'current_court',current_court,'highest_court',highest_court,'season_wins',season_wins,'season_losses',season_losses,'games_played',games_played,'no_show_count',no_show_count,'membership_type',membership_type,'registered_at',registered_at) order by id),'[]'::jsonb) from public.players),
  'state',(select coalesce(jsonb_object_agg(key,value::jsonb),'{}'::jsonb) from public.app_state where key in ('player_approvals','membership_overrides','pre_session_attendance','round_snapshots') or key like 'votes_session_%' or key like 'rsvp_session_%'));
 insert into public.app_state(key,value,version,updated_at) values('archive_'||trim(p_label),archive::text,1,now());
 delete from public.app_state where key in ('completed_sessions','player_approvals','membership_overrides','pre_session_attendance','round_snapshots') or key like 'votes_session_%' or key like 'rsvp_session_%';
 delete from public.rsvps;
 update public.players set season_wins=0,season_losses=0,games_played=0,no_show_count=0,paid=false,approved=false,waitlisted=false,registered_at=null,updated_at=now();
 get diagnostics n=row_count;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'season.started',trim(p_label),jsonb_build_object('players_reset',n));
 return jsonb_build_object('archived',trim(p_label),'players_reset',n);
end $$;
commit;

-- ═══════════ L06_stats_rebuild ═══════════
-- Season statistics are derived, never incremented: rebuild from stored scores after every change.
-- Counts every completed session, plus rounds of the active session that have already rotated (movements).
-- Legacy tied games (w='T') count as played but neither won nor lost, as the old rebuild did.
begin;
create or replace function public.rebuild_player_stats() returns jsonb language plpgsql security definer set search_path='' as $$ declare sessions jsonb; cur jsonb; n int;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 select nullif(value,'null')::jsonb into sessions from public.app_state where key='completed_sessions';
 select nullif(value,'null')::jsonb into cur from public.app_state where key='current_session';
 with games as (
  select e.value as sc from jsonb_array_elements(coalesce(sessions,'[]'::jsonb)) s cross join lateral jsonb_each(case when jsonb_typeof(s->'scores')='object' then s->'scores' else '{}'::jsonb end) e
  union all
  select e.value from jsonb_each(case when cur is not null and jsonb_typeof(cur->'scores')='object' then cur->'scores' else '{}'::jsonb end) e
   where (substring(e.key from '_y([0-9]+)_'))::int in (select (m->>'cycle')::int from jsonb_array_elements(case when cur is not null and jsonb_typeof(cur->'movements')='array' then cur->'movements' else '[]'::jsonb end) m)
 ), sides as (
  select (x#>>'{}')::bigint pid,(sc->>'w')='A' won,(sc->>'w')='B' lost from games cross join lateral jsonb_array_elements(jsonb_build_array(sc->'a1',sc->'a2')) x where jsonb_typeof(x)='number'
  union all
  select (x#>>'{}')::bigint,(sc->>'w')='B',(sc->>'w')='A' from games cross join lateral jsonb_array_elements(jsonb_build_array(sc->'b1',sc->'b2')) x where jsonb_typeof(x)='number'
 ), totals as (select pid,count(*)::int g,count(*) filter(where won)::int w,count(*) filter(where lost)::int l from sides group by pid)
 update public.players p set season_wins=coalesce(t.w,0),season_losses=coalesce(t.l,0),games_played=coalesce(t.g,0),updated_at=now()
 from public.players q left join totals t on t.pid=q.id
 where p.id=q.id and (p.season_wins<>coalesce(t.w,0) or p.season_losses<>coalesce(t.l,0) or p.games_played<>coalesce(t.g,0));
 get diagnostics n=row_count;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'stats.rebuilt',null,jsonb_build_object('players_changed',n));
 return jsonb_build_object('players_changed',n);
end $$;
revoke all on function public.rebuild_player_stats() from public,anon;
grant execute on function public.rebuild_player_stats() to authenticated;
commit;

-- ═══════════ L07_reminders_and_spares ═══════════
-- Reminders and spare seats.
-- * players.email_reminders: each player's own opt-out for reminder emails (default on).
-- * reminder_log: one row per (session, player, kind) so the scheduled job can never email twice.
-- * reminder_targets(): who still needs a nudge for a session — callable only by the service role from the job.
-- * Spare seats are derived, never stored: declined regulars open seats; spares who said "available" fill them in
--   the order they answered (rsvps.updated_at); the rest are standby. The same rule is used by the app and the job.
begin;
alter table public.players add column if not exists email_reminders boolean not null default true;
create table if not exists public.reminder_log(id bigint generated always as identity primary key,session_number int not null,player_id bigint not null references public.players(id) on delete cascade,kind text not null,sent_at timestamptz not null default now(),unique(session_number,player_id,kind));
alter table public.reminder_log enable row level security;
revoke all on public.reminder_log from public,anon,authenticated;
create policy "admin reads reminder log" on public.reminder_log for select to authenticated using(public.is_admin());
grant select on public.reminder_log to authenticated;

create or replace function public.set_email_reminders(p_on boolean) returns void language plpgsql security definer set search_path='' as $$ declare pid bigint;begin
 pid=public.my_player_id();if pid is null then raise exception 'No player record' using errcode='42501';end if;
 update public.players set email_reminders=coalesce(p_on,true),updated_at=now() where id=pid;
end $$;
revoke all on function public.set_email_reminders(boolean) from public,anon;
grant execute on function public.set_email_reminders(boolean) to authenticated;

-- Seats opened by declined regulars minus spares already confirmed, in answer order.
create or replace function public.spare_seats(p_session int) returns table(player_id bigint,rank int,confirmed boolean,open_seats int) language sql stable security definer set search_path='' as $$
 with declined as (
  select count(*)::int n from public.rsvps r join public.players p on p.id=r.player_id
  where r.session_number=p_session and r.response='notcoming' and p.approved and not p.waitlisted and coalesce(p.membership_type,'regular')<>'spare'
 ), claims as (
  select r.player_id,row_number() over(order by r.updated_at,r.player_id)::int rk from public.rsvps r join public.players p on p.id=r.player_id
  where r.session_number=p_session and r.response='coming' and p.approved and p.membership_type='spare'
 )
 select c.player_id,c.rk,c.rk<=d.n,greatest(d.n-(select count(*)::int from claims),0) from claims c cross join declined d
$$;
revoke all on function public.spare_seats(int) from public,anon;
grant execute on function public.spare_seats(int) to authenticated;

-- Reminder targets: approved regulars without an answer ('vote'); spares without an answer while seats are open ('spare').
create or replace function public.reminder_targets(p_session int) returns table(player_id bigint,name text,email text,membership_type text,kind text,open_seats int) language sql stable security definer set search_path='' as $$
 with declined as (
  select count(*)::int n from public.rsvps r join public.players p on p.id=r.player_id
  where r.session_number=p_session and r.response='notcoming' and p.approved and not p.waitlisted and coalesce(p.membership_type,'regular')<>'spare'
 ), claimed as (
  select count(*)::int n from public.rsvps r join public.players p on p.id=r.player_id
  where r.session_number=p_session and r.response='coming' and p.approved and p.membership_type='spare'
 ), seats as (select greatest(d.n-c.n,0) open from declined d cross join claimed c)
 select p.id,p.name,lower(p.email),coalesce(p.membership_type,'regular'),
        case when coalesce(p.membership_type,'regular')='spare' then 'spare' else 'vote' end,seats.open
 from public.players p cross join seats
 where p.approved and not p.waitlisted and p.email_reminders and p.email is not null and position('@' in p.email)>1
   and not exists(select 1 from public.rsvps r where r.session_number=p_session and r.player_id=p.id)
   and (coalesce(p.membership_type,'regular')<>'spare' or seats.open>0)
 order by p.id
$$;
revoke all on function public.reminder_targets(int) from public,anon,authenticated;
grant execute on function public.reminder_targets(int) to service_role;
revoke all on public.reminder_log from service_role; grant select,insert on public.reminder_log to service_role;
commit;

-- ═══════════ L08_payments_and_push ═══════════
-- Payment ledger and push subscriptions.
-- * payments: every e-transfer, spare fee, refund or adjustment as a row; players.paid is derived from it.
-- * push_subscriptions: browser push endpoints a player registered; the reminder job uses them, players own them.
begin;
create table if not exists public.payments(id bigint generated always as identity primary key,player_id bigint not null references public.players(id) on delete cascade,kind text not null check(kind in ('season','spare','refund','adjustment')),amount numeric(8,2) not null check(amount>=0),session_number int,method text not null default 'e-transfer',received_on date not null default current_date,note text not null default '' check(length(note)<=300),created_by uuid,created_at timestamptz not null default now());
alter table public.payments enable row level security;
revoke all on public.payments from public,anon;
create policy "own payments" on public.payments for select to authenticated using(player_id=public.my_player_id() or public.is_admin());
grant select on public.payments to authenticated;
create index if not exists payments_player_idx on public.payments(player_id);

-- Season-fee status derives from the ledger: paid once season payments (plus adjustments) reach the fee for regulars, or once any spare fee exists for spares. Absence refunds are money out and never unpay a season.
create or replace function public.refresh_paid_flag(p_player bigint) returns void language sql security definer set search_path='' as $$
 update public.players p set paid=(
   case when coalesce(p.membership_type,'regular')='spare'
     then exists(select 1 from public.payments x where x.player_id=p.id and x.kind='spare')
     else coalesce((select sum(amount) from public.payments x where x.player_id=p.id and x.kind in('season','adjustment')),0)>=400
   end),updated_at=now()
 where p.id=p_player
$$;
create or replace function public.record_payment(p_player bigint,p_kind text,p_amount numeric,p_session int default null,p_received_on date default current_date,p_note text default '') returns bigint language plpgsql security definer set search_path='' as $$ declare pid bigint;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if not exists(select 1 from public.players where id=p_player) then raise exception 'Unknown player';end if;
 insert into public.payments(player_id,kind,amount,session_number,received_on,note,created_by) values(p_player,p_kind,p_amount,p_session,coalesce(p_received_on,current_date),coalesce(p_note,''),auth.uid()) returning id into pid;
 perform public.refresh_paid_flag(p_player);
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'payment.recorded',p_player::text,jsonb_build_object('id',pid,'kind',p_kind,'amount',p_amount,'session',p_session));
 return pid;
end $$;
create or replace function public.delete_payment(p_id bigint) returns void language plpgsql security definer set search_path='' as $$ declare pl bigint;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 delete from public.payments where id=p_id returning player_id into pl;
 if pl is not null then perform public.refresh_paid_flag(pl); insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'payment.deleted',pl::text,jsonb_build_object('id',p_id)); end if;
end $$;
revoke all on function public.record_payment(bigint,text,numeric,int,date,text) from public,anon;
revoke all on function public.delete_payment(bigint) from public,anon;
revoke all on function public.refresh_paid_flag(bigint) from public,anon,authenticated;
grant execute on function public.record_payment(bigint,text,numeric,int,date,text) to authenticated;
grant execute on function public.delete_payment(bigint) to authenticated;

create table if not exists public.push_subscriptions(id bigint generated always as identity primary key,player_id bigint not null references public.players(id) on delete cascade,endpoint text not null unique check(length(endpoint)<=2000),p256dh text not null,auth text not null,user_agent text not null default '',created_at timestamptz not null default now());
alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from public,anon,authenticated;
create policy "own subscriptions" on public.push_subscriptions for select to authenticated using(player_id=public.my_player_id());
grant select on public.push_subscriptions to authenticated;
create or replace function public.save_push_subscription(p_endpoint text,p_p256dh text,p_auth text,p_user_agent text default '') returns void language plpgsql security definer set search_path='' as $$ declare pid bigint;begin
 pid=public.my_player_id();if pid is null then raise exception 'No player record' using errcode='42501';end if;
 if p_endpoint is null or p_endpoint not like 'https://%' then raise exception 'Invalid subscription';end if;
 insert into public.push_subscriptions(player_id,endpoint,p256dh,auth,user_agent) values(pid,p_endpoint,p_p256dh,p_auth,left(coalesce(p_user_agent,''),200))
 on conflict(endpoint) do update set player_id=excluded.player_id,p256dh=excluded.p256dh,auth=excluded.auth,user_agent=excluded.user_agent,created_at=now();
end $$;
create or replace function public.delete_push_subscription(p_endpoint text) returns void language sql security definer set search_path='' as $$
 delete from public.push_subscriptions where endpoint=p_endpoint and player_id=public.my_player_id()
$$;
revoke all on function public.save_push_subscription(text,text,text,text) from public,anon;
revoke all on function public.delete_push_subscription(text) from public,anon;
grant execute on function public.save_push_subscription(text,text,text,text) to authenticated;
grant execute on function public.delete_push_subscription(text) to authenticated;
-- The reminder job (service role) reads subscriptions for the players it is about to remind and drops dead endpoints.
grant select,delete on public.push_subscriptions to service_role;
grant select on public.payments to service_role;
commit;
