-- Maplewood league migration, 10 October 2026 — PRODUCTION.
-- Generated by legacy/scripts/build-vote-link-migration.mjs. Paste the whole file into the SQL editor of the
-- PRODUCTION project and run it in one go; it is one transaction, so any failure rolls the whole thing back.
-- Afterwards run legacy/migrations/verify.sql: every row must read OK.
--
-- L31  answering a vote reminder from the email, without signing in. Adds vote_links (one 256-bit token per player
--      per session, dead at the voting deadline) and three service-role functions the confirm page uses. The rules a
--      vote must pass move out of set_rsvp into rsvp_write so the emailed path and the app path cannot drift apart;
--      set_rsvp allows exactly what it allowed before.
--
--      NOTE: a link in an inbox is not proof of identity. Anyone who can read a player's email, or who is forwarded
--      it, can answer as that player. That is the cost of not signing in. It is bounded to one player, one session,
--      an answer they can change, expiring at the deadline, and every use counted.
--
-- No player, score, payment or waiver record is read or written: one new table, one new function, four replaced.
begin;
-- This bundle is for the PRODUCTION project (bwepvxelvwgwxrnaglrx) and refuses to run anywhere else.
do $$ begin
 if exists(select 1 from public.environment where name='test') then raise exception 'Refusing: this database is marked test'; end if;
 if not exists(select 1 from public.environment where name='production') then raise exception 'Refusing: this database is not marked production'; end if;
end $$;

-- ═══════════ L31_vote_from_the_email.sql ═══════════
-- L31 (10 October 2026): answering a vote reminder from the email, without signing in.
--
-- The organizer: "just a yes or no click from the mail should apply the vote, here in the app, it should not be
-- opening the app and then make them do, simple click".
--
-- Until now a reminder's Yes/No link was `/?vote=coming&s=5`, which opens the site and applies the answer ONLY once
-- the player has signed in (index.html: "applied once signed in"). For somebody who has not opened the app in weeks
-- that is an email code, a sign-in and a hunt for the right card — which is why the answers do not come.
--
-- WHAT THIS ADDS. A per-player, per-session link that carries its own credential, so the confirm page can record the
-- answer with nobody signed in:
--   vote_links        one row per player per session: a 256-bit token, when it dies, and how often it was used.
--   issue_vote_link   service_role only. Mints (or re-uses) the token for one player and session.
--   vote_link_info    service_role only. What the confirm page needs to show, and whether the token is still good.
--   apply_vote_link   service_role only. Checks the token, then writes the answer through the SAME rules the app uses.
--
-- WHAT IT DELIBERATELY DOES NOT DO. A link in an inbox is not proof of identity: anybody who can read the message, or
-- who is forwarded it, can answer as that player. No design removes that — it is the cost of not signing in. What is
-- bounded is the damage: one player, one session, an answer they can change, dead at the voting deadline, good for
-- nothing else, and every use counted. The token is never a login and grants no read of anybody else's data.
--
-- ONE COPY OF THE RULES. set_rsvp holds the rules a vote must pass (a real session, not cancelled, a known response,
-- the deadline for regulars, the same answer twice being harmless). Rather than restate them for the email path and
-- let the two drift, they move into rsvp_write and set_rsvp now calls it. set_rsvp's own behaviour is unchanged: it
-- still refuses to answer for anybody but you, and the organizer may still answer after the deadline.

-- L18's guard: this file is safe on either database, but keep the habit of saying which one it ran on.
do $$ begin
 if not exists(select 1 from public.environment) then raise exception 'Refusing: this database is not marked'; end if;
end $$;

create table if not exists public.vote_links(
  token         text primary key,
  player_id     bigint not null references public.players(id) on delete cascade,
  session_number int   not null,
  created_at    timestamptz not null default now(),
  expires_at    timestamptz not null,
  use_count     int not null default 0,
  last_used_at  timestamptz,
  last_response text,
  unique(player_id, session_number)
);
alter table public.vote_links enable row level security;
-- No policy, so nobody reaches it through the API; only the reminder worker and the confirm page, which hold the
-- service-role key and never run in a browser.
-- L15 and L21's pattern, and the reason for it: Supabase's default privileges hand every role the full set on a NEW
-- table in public — TRUNCATE, REFERENCES and TRIGGER included. Revoke from service_role too, then grant back only
-- the four the worker actually needs. (verify.sql fails the release otherwise, which is how this was caught.)
revoke all on public.vote_links from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.vote_links to service_role;

-- ── the rules a vote has to pass, stated once ────────────────────────────────────────────────────────────────────
create or replace function public.rsvp_write(p_session int, p_player bigint, p_response text, p_note text,
                                             p_enforce_deadline boolean)
returns void language plpgsql security definer set search_path='' as $$
declare existing public.rsvps;
begin
 if p_response is null or p_response not in ('coming','notcoming','maybe','late','need_spare') then
  raise exception 'Invalid response'; end if;
 if not exists(select 1 from public.season_dates where session_number=p_session and not cancelled) then
  raise exception 'Invalid or cancelled session'; end if;
 perform pg_advisory_xact_lock(7262026);
 select * into existing from public.rsvps where session_number=p_session and player_id=p_player for update;
 -- Same answer is safe to retry even after voting closes; note edits do not reset the answer timestamp.
 if existing.response=p_response then
  if existing.note is distinct from coalesce(p_note,'') then
   update public.rsvps set note=coalesce(p_note,'') where session_number=p_session and player_id=p_player; end if;
  return;
 end if;
 if p_enforce_deadline
  and exists(select 1 from public.players p where p.id=p_player and p.membership_type<>'spare')
  and exists(select 1 from public.season_dates d where d.session_number=p_session
             and now()>d.start_at-public.season_setting('vote_deadline_hours',46)*interval '1 hour')
 then raise exception 'Voting closed for this session. Message the admin in the group to change your answer.'
      using errcode='42501'; end if;
 insert into public.rsvps(session_number,player_id,response,note)
 values(p_session,p_player,p_response,coalesce(p_note,''))
 on conflict(session_number,player_id) do update set response=excluded.response,note=excluded.note,updated_at=now();
end $$;
revoke all on function public.rsvp_write(int,bigint,text,text,boolean) from public,anon,authenticated;

-- Unchanged in what it allows: you answer for yourself, the organizer answers for anyone and is not held to the
-- deadline. The rules themselves now live in one place.
create or replace function public.set_rsvp(p_session int,p_player bigint,p_response text,p_note text default '')
returns void language plpgsql security definer set search_path='' as $$
declare me bigint;
begin
 me=public.my_player_id();
 if not public.is_admin() and (me is null or p_player is distinct from me) then
  raise exception 'You can only answer for yourself' using errcode='42501'; end if;
 perform public.rsvp_write(p_session,p_player,p_response,coalesce(p_note,''), not public.is_admin());
end $$;

-- ── the link ─────────────────────────────────────────────────────────────────────────────────────────────────────
-- 256 bits from gen_random_uuid(), which is the server's strong source. One token per player per session: the Friday
-- and the Sunday email carry the same link, so answering from either works and a forwarded old mail is not a second
-- door. It dies at the voting deadline, not at the session.
create or replace function public.issue_vote_link(p_player bigint, p_session int)
returns text language plpgsql security definer set search_path='' as $$
declare tok text; dies timestamptz;
begin
 if not exists(select 1 from public.players where id=p_player) then raise exception 'No such player'; end if;
 select d.start_at - public.season_setting('vote_deadline_hours',46)*interval '1 hour' into dies
 from public.season_dates d where d.session_number=p_session and not d.cancelled;
 if dies is null then raise exception 'Invalid or cancelled session'; end if;
 select v.token into tok from public.vote_links v
  where v.player_id=p_player and v.session_number=p_session and v.expires_at>now();
 if tok is not null then return tok; end if;
 tok := replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','');
 insert into public.vote_links(token,player_id,session_number,expires_at)
 values(tok,p_player,p_session,dies)
 on conflict(player_id,session_number) do update
   set token=excluded.token, expires_at=excluded.expires_at, created_at=now(), use_count=0,
       last_used_at=null, last_response=null;
 return tok;
end $$;
revoke all on function public.issue_vote_link(bigint,int) from public,anon,authenticated;
grant execute on function public.issue_vote_link(bigint,int) to service_role;

-- What the confirm page shows before anybody presses anything. Reading a token is not answering with it.
create or replace function public.vote_link_info(p_token text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.vote_links; p public.players; d public.season_dates; cur text;
begin
 select * into v from public.vote_links where token=p_token;
 if v.token is null then return jsonb_build_object('status','unknown'); end if;
 select * into p from public.players where id=v.player_id;
 select * into d from public.season_dates where session_number=v.session_number;
 select r.response into cur from public.rsvps r
  where r.session_number=v.session_number and r.player_id=v.player_id;
 return jsonb_build_object(
   'status', case when v.expires_at<=now() then 'closed' else 'ok' end,
   'name', p.name, 'first_name', split_part(p.name,' ',1),
   'session', v.session_number, 'play_on', d.play_on, 'start_at', d.start_at,
   'closes_at', v.expires_at, 'current', cur, 'cancelled', coalesce(d.cancelled,false));
end $$;
revoke all on function public.vote_link_info(text) from public,anon,authenticated;
grant execute on function public.vote_link_info(text) to service_role;

-- Answering. Only the two answers a reminder asks for; everything else a player does from the app as before.
create or replace function public.apply_vote_link(p_token text, p_response text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.vote_links; p public.players;
begin
 if p_response not in ('coming','notcoming') then
  return jsonb_build_object('status','bad_response'); end if;
 select * into v from public.vote_links where token=p_token for update;
 if v.token is null then return jsonb_build_object('status','unknown'); end if;
 if v.expires_at<=now() then return jsonb_build_object('status','closed'); end if;
 perform public.rsvp_write(v.session_number, v.player_id, p_response, '', true);
 update public.vote_links set use_count=use_count+1, last_used_at=now(), last_response=p_response
  where token=p_token;
 select * into p from public.players where id=v.player_id;
 return jsonb_build_object('status','ok','response',p_response,'session',v.session_number,
                           'name',p.name,'first_name',split_part(p.name,' ',1));
end $$;
revoke all on function public.apply_vote_link(text,text) from public,anon,authenticated;
grant execute on function public.apply_vote_link(text,text) to service_role;

-- L26: create or replace throws a function's SET clauses away, so the bounds go back on. verify.sql refuses an
-- unbounded lock-taker, and rsvp_write takes the league lock.
alter function public.rsvp_write(int,bigint,text,text,boolean) set lock_timeout='5s';
alter function public.rsvp_write(int,bigint,text,text,boolean) set statement_timeout='20s';
alter function public.set_rsvp(int,bigint,text,text)           set lock_timeout='5s';
alter function public.set_rsvp(int,bigint,text,text)           set statement_timeout='20s';
alter function public.issue_vote_link(bigint,int)              set lock_timeout='5s';
alter function public.issue_vote_link(bigint,int)              set statement_timeout='20s';
alter function public.vote_link_info(text)                     set lock_timeout='5s';
alter function public.vote_link_info(text)                     set statement_timeout='20s';
alter function public.apply_vote_link(text,text)               set lock_timeout='5s';
alter function public.apply_vote_link(text,text)               set statement_timeout='20s';
commit;
