-- Maplewood league migration, 6 October 2026 — PRODUCTION.
-- Generated by legacy/scripts/build-october-migration.mjs. Paste the whole file into the SQL editor of the PRODUCTION
-- project and run it in one go; it is one transaction, so any failure rolls all three migrations back together.
-- Afterwards run legacy/migrations/verify.sql: every row must read OK.
--
-- L28  the organizer's hand-made court moves and a drop-in's starting points are part of Undo, and are cleared at
--      season rollover. Without it, Undo put a court back and left the adjustment behind.
-- L29  set_regular_capacity: the organizer can change how many regular places the season has (2 to 30, never below the
--      regulars already approved, written to audit_log). Without it the app can ask to go over the cap and the database
--      refuses, which is worse than not asking.
-- L30  one rule for the spare seats. spare_seat_status and reminder_targets each kept their own copy (one seat per
--      decline); on the 4 October data the app, spare_seat_status and reminder_targets gave 4, 2 and 2 for one night.
--      NOTE: more spares can hold a reserved seat than before, so the reminder worker can send more "your seat is
--      reserved" messages. That is the fix working, and it is a change in what players receive.
--
-- No player, score, payment or waiver record is read or written by any of this: it replaces four function bodies and
-- adds one.
begin;
-- This bundle is for the PRODUCTION project (bwepvxelvwgwxrnaglrx) and refuses to run anywhere else.
do $$ begin
 if exists(select 1 from public.environment where name='test') then raise exception 'Refusing: this database is marked test'; end if;
 if not exists(select 1 from public.environment where name='production') then raise exception 'Refusing: this database is not marked production'; end if;
end $$;

-- ═══════════ L28_organizer_keys_in_undo_and_rollover.sql ═══════════
-- L28 (5 October 2026): the two keys the organizer's own decisions live in are part of undo, and are cleared at rollover.
--
-- p92 introduced app_state.admin_court_moves (the running total of courts the organizer moved a player by hand, added
-- back so a courtesy move is not recorded as a court drop) and p99 introduces app_state.player_seed_points (the starting
-- rating the organizer sets for a drop-in). Both were left out of two lists that already existed:
--
-- 1. UNDO. capture_state()/undo_last() snapshot and restore five app_state keys. A seat change (setPlayerCourt) is an
--    undoable action and writes admin_court_moves, so pressing Undo put the court back and left the adjustment behind:
--    the court-climb figure then counted a move that no longer existed. Same for a drop-in's starting points.
-- 2. SEASON ROLLOVER. rollover_season_internal archives and clears the season's app_state keys. These two were neither
--    archived nor cleared, so last season's hand-made court moves and starting points would have carried into the new
--    season and skewed the first night's figures and ratings.
--
-- Nothing else changes. The three bodies below are the current ones (all three from L24) with the two key names added to
-- each list. undo_last takes the league lock, so L26's bounds (lock_timeout 5s, statement_timeout 20s) are re-applied
-- afterwards: CREATE OR REPLACE replaces a function's SET clauses, and verify.sql refuses an unbounded lock-taker.

create or replace function public.capture_state() returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object(
  'app_state',(select coalesce(jsonb_object_agg(key,to_jsonb(value)),'{}'::jsonb) from public.app_state
               where key in ('current_session','completed_sessions','player_approvals','membership_overrides','pre_session_attendance','admin_court_moves','player_seed_points')),
  'players',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'current_court',current_court,'highest_court',highest_court,'no_show_count',no_show_count,
               'approved',approved,'waitlisted',waitlisted,'membership_type',membership_type,'season_wins',season_wins,'season_losses',season_losses,
               'games_played',games_played,'archived_at',archived_at) order by id),'[]'::jsonb) from public.players))
$$;
revoke all on function public.capture_state() from public,anon,authenticated;

create or replace function public.undo_last() returns jsonb language plpgsql security definer set search_path='' as $$
declare e public.undo_journal; k text; st jsonb;
begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501'; end if;
 perform pg_advisory_xact_lock(7262026);
 perform 1 from public.app_state where key in ('current_session','completed_sessions','player_approvals','membership_overrides','pre_session_attendance','admin_court_moves','player_seed_points') for update;
 select * into e from public.undo_journal order by id desc limit 1 for update;
 if e.id is null then raise exception 'Nothing to undo'; end if;
 if exists(select 1 from public.audit_log a where a.action='season.started' and a.created_at>e.created_at) then
  raise exception 'Nothing to undo since the new season started';
 end if;
 if e.snapshot=public.capture_state() then -- that step changed nothing (e.g. a dialog was cancelled): drop it, undo nothing else
  delete from public.undo_journal where id=e.id;
  return jsonb_build_object('undone',null,'skipped',e.label,'taken_at',e.created_at,'remaining',(select count(*) from public.undo_journal));
 end if;
 st=e.snapshot->'app_state';
 foreach k in array array['current_session','completed_sessions','player_approvals','membership_overrides','pre_session_attendance','admin_court_moves','player_seed_points'] loop
  if st ? k then
   insert into public.app_state(key,value,version,updated_at) values(k,st->>k,1,now())
   on conflict(key) do update set value=excluded.value,version=public.app_state.version+1,updated_at=now();
  else
   delete from public.app_state where key=k;
  end if;
 end loop;
 update public.players p set current_court=(x->>'current_court')::int,highest_court=(x->>'highest_court')::int,no_show_count=(x->>'no_show_count')::int,
   archived_at=case when x?'archived_at' then (x->>'archived_at')::timestamptz else p.archived_at end,approved=(x->>'approved')::boolean,waitlisted=(x->>'waitlisted')::boolean,membership_type=x->>'membership_type',
   season_wins=(x->>'season_wins')::int,season_losses=(x->>'season_losses')::int,games_played=(x->>'games_played')::int,updated_at=now()
 from jsonb_array_elements(e.snapshot->'players') x where p.id=(x->>'id')::bigint;
 delete from public.undo_journal where id=e.id;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'undo',e.label,jsonb_build_object('journal_id',e.id,'taken_at',e.created_at));
 return jsonb_build_object('undone',e.label,'taken_at',e.created_at,'remaining',(select count(*) from public.undo_journal));
end $$;
revoke all on function public.undo_last() from public,anon;
grant execute on function public.undo_last() to authenticated;

create or replace function public.rollover_season_internal(p_label text) returns jsonb language plpgsql security definer set search_path='' as $$ declare archive jsonb; sessions text; cur text; n int; np int;begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if p_label is null or length(trim(p_label)) not between 3 and 40 or exists(select 1 from public.app_state where key='archive_'||trim(p_label)) then raise exception 'Unique archive label required';end if;
 select value into sessions from public.app_state where key='completed_sessions';
 select value into cur from public.app_state where key='current_session';
 if cur is not null and cur<>'null' then raise exception 'End the active session before starting a new season';end if;
 archive=jsonb_build_object('label',trim(p_label),'archived_at',now(),'completed_sessions',coalesce(sessions,'[]')::jsonb,
  'players',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'current_court',current_court,'highest_court',highest_court,'season_wins',season_wins,'season_losses',season_losses,'games_played',games_played,'no_show_count',no_show_count,'membership_type',membership_type,'registered_at',registered_at) order by id),'[]'::jsonb) from public.players),
  'state',(select coalesce(jsonb_object_agg(key,value::jsonb),'{}'::jsonb) from public.app_state where key in ('player_approvals','membership_overrides','pre_session_attendance','round_snapshots','admin_court_moves','player_seed_points') or key like 'votes_session_%' or key like 'rsvp_session_%'));
 insert into public.app_state(key,value,version,updated_at) values('archive_'||trim(p_label),archive::text,1,now());
 delete from public.app_state where key in ('completed_sessions','player_approvals','membership_overrides','pre_session_attendance','round_snapshots','admin_court_moves','player_seed_points') or key like 'votes_session_%' or key like 'rsvp_session_%';
 insert into public.payments_archive(id,season_label,player_id,player_name,kind,amount,session_number,method,received_on,note,created_by,created_at)
  select x.id,trim(p_label),x.player_id,p.name,x.kind,x.amount,x.session_number,x.method,x.received_on,x.note,x.created_by,x.created_at
  from public.payments x left join public.players p on p.id=x.player_id on conflict(id) do nothing;
 delete from public.payments where true;
 get diagnostics np=row_count;
 delete from public.reminder_log where true;
 delete from public.rsvps where true;
 update public.players set season_wins=0,season_losses=0,games_played=0,no_show_count=0,paid=false,approved=false,waitlisted=false,registered_at=null,updated_at=now() where true;
 get diagnostics n=row_count;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'season.started',trim(p_label),jsonb_build_object('players_reset',n,'payments_archived',np));
 return jsonb_build_object('archived',trim(p_label),'players_reset',n,'payments_archived',np);
end $$;
revoke all on function public.rollover_season_internal(text) from public,anon,authenticated,service_role;

-- L26 again, for whatever this migration replaced: a function that takes the league lock must be bounded.
do $$
declare r record; n int := 0;
begin
 for r in
   select p.oid::regprocedure as sig
   from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where ns.nspname = 'public' and p.prosrc like '%pg_advisory_xact_lock(7262026)%'
     and not (coalesce(array_to_string(p.proconfig,','),'') like '%lock_timeout%' and coalesce(array_to_string(p.proconfig,','),'') like '%statement_timeout%')
 loop
   execute format('alter function %s set lock_timeout = %L', r.sig, '5s');
   execute format('alter function %s set statement_timeout = %L', r.sig, '20s');
   n := n + 1;
 end loop;
 raise notice 'L28: re-bounded % lock-taking function(s)', n;
end $$;

-- ═══════════ L29_regular_capacity.sql ═══════════
-- L29 (5 October 2026): the organizer can add a regular place to the season.
--
-- From the organizer: "admin should be able to approve the waitlist and make a player regular, even if the cap is
-- reached". p100 does that in the app, but the database refused it underneath, in two places:
--   * set_state('player_approvals'/'membership_overrides', …) — "Regular places are full; keep the player on the
--     waitlist" once the approved regulars reach regular_capacity;
--   * add_league_player(…, 'regular') — "Regular places are full".
-- So the app would have asked the organizer to confirm and then failed with a database error.
--
-- The cap is a season setting and the only way to change it was start_new_season, which archives the season. This
-- migration adds one function so the number can be moved during a season, by the organizer, on the record:
--
--   set_regular_capacity(p_capacity int) -> int
--
-- Organizer only (aal2, like every other admin function). Bounded 2..30, the same range start_new_season validates.
-- It will not be set below the regulars already approved, so the setting can never contradict the roster. Every change
-- is written to audit_log with the old and new number. Nothing else changes: the cap still stops the registration form
-- overfilling the season — at whatever number the organizer has set.

create or replace function public.set_regular_capacity(p_capacity int) returns int language plpgsql security definer set search_path='' as $$
declare st public.app_state; cfg jsonb; was int; have int;
begin
 if not public.is_admin() then raise exception 'Organizer verification required' using errcode='42501';end if;
 if p_capacity is null or p_capacity not between 2 and 30 then raise exception 'Regular places must be a number from 2 to 30';end if;
 perform pg_advisory_xact_lock(7262026);
 select * into st from public.app_state where key='season_config' for update;
 if st.key is null then raise exception 'No season is configured';end if;
 cfg=st.value::jsonb;
 was=coalesce((cfg->>'regular_capacity')::int,0);
 select count(*) into have from public.players where archived_at is null and approved and not waitlisted and membership_type='regular';
 if p_capacity<have then raise exception 'There are already % regular members; the number cannot be set below that',have;end if;
 if p_capacity=was then return was;end if;
 update public.app_state set value=(cfg||jsonb_build_object('regular_capacity',p_capacity))::text,version=version+1,updated_at=now() where key='season_config';
 insert into public.audit_log(actor,action,subject,detail)
  values(auth.uid(),'season.capacity',p_capacity::text,jsonb_build_object('was',was,'now',p_capacity,'regulars',have));
 return p_capacity;
end $$;
revoke all on function public.set_regular_capacity(int) from public,anon,service_role;
grant execute on function public.set_regular_capacity(int) to authenticated;
alter function public.set_regular_capacity(int) set lock_timeout = '5s';
alter function public.set_regular_capacity(int) set statement_timeout = '20s';

-- ═══════════ L30_spare_seats_match_the_app.sql ═══════════
-- L30 (5 October 2026): the database counts spare seats by the same rule as the app, in one place.
--
-- THE MISMATCH, measured on the production backup of 4 October (Session 4: 25 regulars with a court, 20 said coming,
-- 2 said not coming, 3 never answered, 1 spare available):
--     the app showed                                            1 spare seat   (24 - the regulars not declining)
--     the app shows after p96                                   4 spare seats  (24 - the regulars who said coming)
--     spare_seat_status() said                                  2 spare seats  (one per decline)
--     reminder_targets()   said                                 2 spare seats  (its own copy of the same rule)
-- Four numbers for one night, from three rules written three times. The rule the organizer agreed (p69, 14 September:
-- "we have 27 regular players, if say 4 of them voted no, we will take in one spare") is that the spares fill the courts
-- up to 24 players — six courts of four. One seat per decline only coincides with that when exactly 24 regulars hold a
-- court; with 25 it under-counted, and with fewer than 24 it under-counted badly.
--
-- This matters because those two functions drive what players receive: who is told "your seat is reserved"
-- (spare_reservation_targets, built on spare_seat_status) and which spares are asked whether they are available
-- (reminder_targets). Under-counting meant a spare who really had a seat was never asked, while the organizer's own
-- screen said a seat was open.
--
-- Now there is ONE rule, in spare_seat_count: 24 minus the regulars who said "coming" (or whom the organizer marked
-- present before the night), leaving out anyone marked absent and anyone archived. Both functions use it. Nothing else
-- about either changes — the order spares are ranked in (answer time, then id), what counts as paid, who is skipped for
-- having answered already or turned reminders off, and the shape of both results are untouched.
--
-- NOTE for whoever applies this to production: more spares can hold a reserved seat and more can be asked whether they
-- are available, so the reminder worker can send more messages than it used to. That is the point of the fix, but it is
-- a change in what players receive, so it needs the organizer's explicit go-ahead before production.

-- Six courts of four: the spares fill tonight up to 24 players. Silence is not a yes (p96).
create or replace function public.spare_seat_count(p_session int) returns int language sql stable security definer set search_path='' as $$
 with pre as (select coalesce((select value::jsonb from public.app_state where key='pre_session_attendance'),'{}'::jsonb) j)
 select greatest(24-(
   select count(*)::int
   from public.players p cross join pre
   where p.approved and not p.waitlisted and p.archived_at is null and coalesce(p.membership_type,'regular')<>'spare'
     and coalesce(p.current_court,0)>0
     and coalesce(pre.j->>p.id::text,'') <> 'absent'
     and ((select r.response from public.rsvps r where r.session_number=p_session and r.player_id=p.id)='coming'
          or coalesce(pre.j->>p.id::text,'')='present')),0)
$$;
revoke all on function public.spare_seat_count(int) from public,anon;
grant execute on function public.spare_seat_count(int) to authenticated,service_role;

create or replace function public.spare_seat_status(p_session int) returns table(player_id bigint,rank int,reserved boolean,paid boolean,confirmed boolean,open_seats int) language sql stable security definer set search_path='' as $$
 with seats as (select public.spare_seat_count(p_session) n),
 claims as (select r.player_id,row_number() over(order by r.updated_at,r.player_id)::int rk,
                   coalesce((select sum(amount) from public.payments x where x.player_id=p.id and x.kind='spare' and x.session_number=p_session),0)>=public.season_setting('spare_session',20) pd
            from public.rsvps r join public.players p on p.id=r.player_id
            where r.session_number=p_session and r.response='coming' and p.approved and not p.waitlisted and p.archived_at is null and p.membership_type='spare')
 select c.player_id,c.rk,c.rk<=s.n,c.pd,c.rk<=s.n and c.pd,greatest(s.n-(select count(*)::int from claims),0)
 from claims c cross join seats s
$$;
revoke all on function public.spare_seat_status(int) from public,anon;
grant execute on function public.spare_seat_status(int) to authenticated,service_role;

create or replace function public.reminder_targets(p_session int) returns table(player_id bigint,name text,email text,membership_type text,kind text,open_seats int) language sql stable security definer set search_path='' as $$
 with claimed as (
  select count(*)::int n from public.rsvps r join public.players p on p.id=r.player_id
  where r.session_number=p_session and r.response='coming' and p.approved and not p.waitlisted and p.archived_at is null and p.membership_type='spare'
 ), seats as (select greatest(public.spare_seat_count(p_session)-c.n,0) open from claimed c)
 select p.id,p.name,lower(p.email),coalesce(p.membership_type,'regular'),
        case when coalesce(p.membership_type,'regular')='spare' then 'spare' else 'vote' end,seats.open
 from public.players p cross join seats
 where p.approved and not p.waitlisted and p.archived_at is null and p.email_reminders and p.email is not null and position('@' in p.email)>1
   and not exists(select 1 from public.rsvps r where r.session_number=p_session and r.player_id=p.id)
   and (coalesce(p.membership_type,'regular')<>'spare' or seats.open>0)
 order by p.id
$$;
revoke all on function public.reminder_targets(int) from public,anon,authenticated;
grant execute on function public.reminder_targets(int) to service_role;
commit;
