-- ROLLBACK for the September 2026 release (L19, L20). Generated by legacy/scripts/build-rollback-sql.py; do not edit.
-- PREPARED ONLY. Run it together with putting the previous site back, and on production only with the organizer's
-- approval (docs/28 section 9). The previous site registers through the 7-argument register_me, which L20 removed.
-- What it does:
--   1. register_me: removes L20's 16-argument version and restores the 7-argument version exactly as L10 wrote it. The
--      two can't exist together: the new one's extra arguments have defaults, so a 7-argument call would be ambiguous.
--   2. save_court_scores: restores L15's version (without L19's best-of-three check).
-- What it keeps: the environment marker, the waiver wording, every acceptance record (records are never deleted) and
-- L21's privileges. Registrations through the previous site have no acceptance record.
-- It changes nothing unless the database has exactly this release's versions of both functions.
begin;
do $$ begin
 if to_regprocedure('public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text)') is null or (select md5(prosrc) from pg_proc where oid=to_regprocedure('public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text)'))<>'dcc5d16a268846bf4a4ecaa83dba1336'
 then raise exception 'register_me is not the version from this release (L20) — nothing was changed'; end if;
 if (select md5(prosrc) from pg_proc where oid=to_regprocedure('public.save_court_scores(int,int,jsonb,int)'))<>'7f9491ebcbf4a06f40744dda4ec0a4a3'
 then raise exception 'save_court_scores is not the version from this release (L19) — nothing was changed'; end if;
end $$;
drop function public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text);
create or replace function public.register_me(p_name text,p_phone text,p_emergency text,p_medical text,p_sig text,p_membership text,p_payment text default '') returns bigint language plpgsql security definer set search_path='' as $$ declare em text; inv public.invitations; existing public.players; pid bigint; pay text; begin
 select lower(trim(email)) into em from auth.users where id=auth.uid() and email_confirmed_at is not null;
 if em is null then raise exception 'Verified sign-in email required' using errcode='42501';end if;
 select * into inv from public.invitations where email=em;
 select * into existing from public.players where user_id=auth.uid() or (user_id is null and lower(email)=em) order by user_id is not null desc limit 1;
 if existing.id is null and inv.email is null and not public.is_admin_any_factor() then raise exception 'Registration is closed. This link is for players Christy has confirmed; contact the organizer if you were accepted.' using errcode='42501';end if;
 if p_name is null or length(trim(p_name)) not between 2 and 80 or coalesce(length(p_phone),0)>40 or coalesce(length(p_emergency),0)>200 or coalesce(length(p_medical),0)>500 or coalesce(length(p_sig),0)>200000 then raise exception 'Invalid registration details';end if;
 pay=case when p_payment in ('paid_full','will_pay','per_session') then p_payment else '' end;
 if existing.id is null then
  insert into public.players(name,email,phone,emergency,medical,sig,waiver_signed,paid,current_court,highest_court,season_wins,season_losses,games_played,membership_type,approved,waitlisted,registered_at,user_id,declared_payment)
  values(trim(p_name),em,coalesce(p_phone,''),coalesce(p_emergency,''),coalesce(p_medical,''),coalesce(p_sig,''),p_sig is not null and p_sig<>'',false,0,0,0,0,0,coalesce(inv.membership_type,p_membership,'regular'),false,false,now(),auth.uid(),pay) returning id into pid;
 else
  update public.players set name=trim(p_name),phone=coalesce(p_phone,phone),emergency=coalesce(p_emergency,emergency),medical=coalesce(p_medical,medical),sig=case when p_sig is not null and p_sig<>'' then p_sig else sig end,waiver_signed=(p_sig is not null and p_sig<>'') or waiver_signed,membership_type=coalesce(inv.membership_type,membership_type),registered_at=now(),user_id=auth.uid(),declared_payment=case when pay<>'' then pay else declared_payment end,updated_at=now() where id=existing.id returning id into pid;
 end if;
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'player.registered',pid::text,jsonb_build_object('payment',pay));
 return pid;
end $$;
revoke all on function public.register_me(text,text,text,text,text,text,text) from public,anon;
grant execute on function public.register_me(text,text,text,text,text,text,text) to authenticated;
create or replace function public.save_court_scores(p_court int,p_cycle int,p_scores jsonb,p_expected int) returns int language plpgsql security definer set search_path='' as $$
declare st public.app_state; cur jsonb; assigned jsonb; n int; target int; games int; k text; sc jsonb; sa int; sb int; me bigint; cnt int=0; ids bigint[]; need int; g int;begin
 me=public.my_player_id();
 select * into st from public.app_state where key='current_session' for update;
 if st.key is null then raise exception 'No active session';end if;
 cur=st.value::jsonb;
 if p_expected is not null and p_expected<>st.version then raise exception 'Stale state: refresh before saving' using errcode='40001';end if;
 if coalesce((cur->>'cycle')::int,1)<>p_cycle then raise exception 'That round is over — refresh to see the current round' using errcode='40001';end if;
 if coalesce((cur->>'completed')::boolean,false) then raise exception 'Session is complete; scores are locked';end if;
 if p_court is null or p_court not between 1 and 6 then raise exception 'Invalid court';end if;
 assigned=coalesce(cur->'assignments'->(p_court::text),'[]'::jsonb);
 n=jsonb_array_length(assigned);
 if not public.is_admin() then
  if me is null or not exists(select 1 from jsonb_array_elements(assigned) e where (e#>>'{}')::bigint=me) then raise exception 'Only players on this court (or the organizer) can enter its scores' using errcode='42501';end if;
 end if;
 if n<2 then raise exception 'Court % needs at least two players',p_court;end if;
 target=case when n=5 then 15 else 21 end;
 games=case when n=5 then 5 else 3 end;
 need=case when n>=4 then 4 else 2 end;
 if jsonb_typeof(p_scores)<>'object' then raise exception 'Invalid scores';end if;
 for k,sc in select * from jsonb_each(p_scores) loop
  if k !~ ('^c'||p_court||'_y'||p_cycle||'_g[1-5]$') then raise exception 'Score key % is not on this court/round',k;end if;
  g=substring(k from '_g([1-5])$')::int;
  if g>games then raise exception 'Court % plays % games; % is not one of them',p_court,games,k;end if;
  sa=(sc->>'sA')::int;sb=(sc->>'sB')::int;
  if sa is null or sb is null or sa<0 or sb<0 or sa=sb or greatest(sa,sb)<>target or least(sa,sb)>=target then raise exception 'Game % must finish at % with no tie',k,target;end if;
  if (sc->>'w') is distinct from (case when sa>sb then 'A' else 'B' end) then raise exception 'Winner flag does not match the score for %',k;end if;
  select array_agg(v) into ids from (select (sc->>f)::bigint v from unnest(array['a1','a2','b1','b2']) f where jsonb_typeof(sc->f)='number') t;
  if coalesce(array_length(ids,1),0)<>need or (sc->'a1') is null or (sc->'b1') is null
     or (select count(distinct x) from unnest(ids) x)<>need
     or exists(select 1 from unnest(ids) x where not exists(select 1 from jsonb_array_elements(assigned) e where (e#>>'{}')::bigint=x))
  then raise exception 'Game % must be played by % different players from Court %',k,need,p_court;end if;
  cur=jsonb_set(cur,array['scores',k],sc,true);cnt=cnt+1;
 end loop;
 if cnt=0 then raise exception 'No scores supplied';end if;
 insert into public.undo_journal(actor,actor_email,label,snapshot)
 values(auth.uid(),public.my_email(),'Scores: Court '||p_court||', Round '||p_cycle||coalesce(' · '||(select name from public.players where id=me),''),public.capture_state());
 update public.app_state set value=cur::text,version=version+1,updated_at=now() where key='current_session';
 insert into public.audit_log(actor,action,subject,detail) values(auth.uid(),'scores.saved','court '||p_court,jsonb_build_object('cycle',p_cycle,'games',cnt,'version',st.version+1));
 return st.version+1;
end $$;
update public.environment set schema_version=schema_version||' (L19/L20 functions rolled back)';
end;
select 'register_me (7 arguments, L10)' as check_name, case when md5(prosrc)='04d96d172bfa33add059a202f0270d49' then 'OK' else 'FAIL' end as result from pg_proc where oid=to_regprocedure('public.register_me(text,text,text,text,text,text,text)')
union all select 'register_me (16 arguments) removed', case when to_regprocedure('public.register_me(text,text,text,text,text,text,text,text,text,text,text,int,text,text,boolean,text)') is null then 'OK' else 'FAIL' end
union all select 'save_court_scores (L15)', case when md5(prosrc)='e2255fa62e57650d3609fc7547a95d7f' then 'OK' else 'FAIL' end from pg_proc where oid=to_regprocedure('public.save_court_scores(int,int,jsonb,int)')
union all select 'waiver records kept', count(*)::text||' records' from public.waiver_acceptances;
